### ISSUE TITLE
AttributeError when finder has no __module__

### ISSUE THREAD

**Issue by jaraco** [python/importlib_metadata#110]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on Jan 29, 2020, 01:19

As reported in #91:

[The fix for #91] broke compatibility with [PyOxidizer](https://github.com/indygreg/PyOxidizer) whose finder is not attached to a module:

```
Traceback (most recent call last):
  [...]
  File "importlib_metadata", line 471, in <module>
  File "importlib_metadata._compat", line 62, in install
  File "importlib_metadata._compat", line 79, in disable_stdlib_finder
  File "importlib_metadata._compat", line 76, in matches
AttributeError: 'PyOxidizerFinder' object has no attribute '__module__'
```

**Comment by jaraco** [comment]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on Jan 29, 2020, 01:59

mentioned in commit a6dbe33324c51f02c6c67317800b10f2a59bcddf

**Comment by jaraco** [comment]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on Jan 29, 2020, 02:06

mentioned in commit 98b91d28363d69bff129d59ba81d5af6f85dabf5

**Comment by jaraco** [comment]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on Jan 29, 2020, 02:06

mentioned in commit 725935ba63470f10370a2485e4a5911b78b2d7ea

**Comment by jaraco** [comment]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on Jan 29, 2020, 02:08

mentioned in merge request !112

**Comment by jaraco** [comment]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on Jan 29, 2020, 02:20

closed via merge request !112

**Comment by jaraco** [comment]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on Jan 29, 2020, 02:20

mentioned in commit 3150ed4da9e1267d0787c6f4c1f8258a26a1dd93
