### ISSUE TITLE
Mixing of pathlib and pathlib2

### ISSUE THREAD

**Issue by jaraco** [python/importlib_metadata#116]
In GitLab by [@mignon.cicchetti](https://gitlab.com/mignon.cicchetti) on Mar 20, 2020, 18:00

*importlib_metadata* mixes *pathlib* and *pathlib2* on python <=3.5 if both are installed.

If both *pathlib* and *pathlib2* are installed on a python distribution <= 3.5, then the test suite passes Path objects of *pathlib* to functions of *pathlib2*.
The issue manifests itself when running the test suite in the form of the following error
```
======================================================================
ERROR: test_distribution_at_pathlib (importlib_metadata.tests.test_api.OffSysPathTests)
Demonstrate how to load metadata direct from a directory.
----------------------------------------------------------------------
Traceback (most recent call last):
File ".../importlib_metadata/tests/test_api.py", line 170, in test_distribution_at_pathlib
dist = Distribution.at(dist_info_path)
File ".../importlib_metadata/__init__.py", line 222, in at
return PathDistribution(pathlib.Path(path))
File "/usr/lib64/python2.7/site-packages/pathlib2/__init__.py", line 1192, in new
self = cls._from_parts(args, init=False)
File "/usr/lib64/python2.7/site-packages/pathlib2/__init__.py", line 848, in from_parts
drv, root, parts = self._parse_args(args)
File "/usr/lib64/python2.7/site-packages/pathlib2/_init__.py", line 840, in _parse_args
% type(a))
TypeError: argument should be a str object or an os.PathLike object returning str, not <class 'pathlib.PosixPath'>

----------------------------------------------------------------------
```

I spare you the code analysis and just point out the imports:

`importlib_metadata/tests/fixtures.py`:
```
try:
import pathlib
except ImportError:
import pathlib2 as pathlib
```

`importlib_metadata/_compat.py`:
```
if sys.version_info > (3, 5): # pragma: nocover
import pathlib
else: # pragma: nocover
import pathlib2 as pathlib
```

Making these imports consistent (preferably using the version of `_compat.py`) solves the issue.

And while we are at it: These imports (*pathlib* on python >3.5, *pathlib2* on python<=3.5) do not coincide with the advertised dependencies in setup.cfg:
```
python_requires = >=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*

install_requires =
zipp>=0.5
pathlib2; python_version < '3'
contextlib2; python_version < '3'
```

Note: I haven't done any analysis with respect to *contextlib* and *contextlib2*. So maybe there is another mixup hiding.

**Comment by jaraco** [comment]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on Mar 25, 2020, 16:39

Thanks for the report. Agreed, it should be consistent. The issue probably stems from a time when the test suite used pathlib, but the library didn't.

Weird that the example you give is Python 2.7, and yet somehow you have `pathlib`. That's unexpected. In my environment, when I `import pathlib` on Python 2.7, I get an `ImportError`, so those two import blocks should be equivalent. Do you have some other `pathlib` installed in the Python 2.7 environment?

> These imports (*pathlib* on python >3.5, *pathlib2* on python<=3.5) do not coincide with the advertised dependencies in setup.cfg:

Given that this project doesn't support Python 3.4, isn't `python_version < '3'` equivalent to `python_version < '3.5'`?

**Comment by jaraco** [comment]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on Mar 25, 2020, 16:46

closed via commit 0ea5172f4f452455862fa0dd0dd8753fae334cee

**Comment by jaraco** [comment]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on Mar 25, 2020, 16:57

mentioned in commit 0ea5172f4f452455862fa0dd0dd8753fae334cee

**Comment by jaraco** [comment]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on Mar 25, 2020, 16:58

Fixed in v1.5.1.

**Comment by jaraco** [comment]
In GitLab by [@mignon.cicchetti](https://gitlab.com/mignon.cicchetti) on Mar 25, 2020, 20:44

Thanks for taking care of this.

>> These imports (pathlib on python >3.5, pathlib2 on python<=3.5) do not coincide with the advertised dependencies in setup.cfg:
>
> Given that this project doesn't support Python 3.4, isn't python_version < '3' equivalent to python_version < '3.5'?

Your statement is true but that's not what I was pointing out. The things to note is that you test against 3.5 but only with strictly greater and strictly smaller, ignoring the equals case.
So for a 3.5 python_version we have
* from setup.cfg (it's not < 3.5): **not** (necessarily) pathlib2
* from the import code (it's not > 3.5): **needs** pathlib2

Hope that makes it clear were the problem lies.

**Comment by jaraco** [comment]
In GitLab by [@mignon.cicchetti](https://gitlab.com/mignon.cicchetti) on Mar 25, 2020, 20:44

reopened

**Comment by jaraco** [comment]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on Mar 25, 2020, 20:53

You may be onto something, though I think everything works at the boundary. Can you demonstrate or describe a condition where things won’t work as expected?

**Comment by jaraco** [comment]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on Mar 26, 2020, 01:48

Python 3.5.0 does actually report `> (3,5)`:

```
>>> (3, 5, 0) > (3, 5)
True
```

I'm going to close this, but feel free to provide a demonstration of a problem.

**Comment by jaraco** [comment]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on Mar 26, 2020, 01:48

closed

**Comment by jaraco** [comment]
In GitLab by [@mignon.cicchetti](https://gitlab.com/mignon.cicchetti) on Mar 27, 2020, 09:14

> Python 3.5.0 does actually report > (3,5):
> ```
> >>> (3, 5, 0) > (3, 5)
> True
> ```

Ahh, my bad. I missed the micro/releaselevel/serial part of the sys.version_info in combination with the counter-intuitive `>`. Thanks for having a second look.more.
