### ISSUE TITLE
ImportError: No module named backports.configparser

### ISSUE THREAD

**Issue by jaraco** [python/importlib_metadata#118]
In GitLab by [@splashcd](https://gitlab.com/splashcd) on Mar 27, 2020, 01:27

My python 2.7 project, which imports celery 4.4.2, failed to run when deployed today, March 26th.

This project last successfully deployed and ran on Tuesday, March 24th.

A new version of `configparser` was released yesterday, March 25th.

Stacktrace:

<pre>Traceback (most recent call last):
  File "/usr/local/bin/celery", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/celery/__main__.py", line 15, in main
    from celery.bin.celery import main as _main
  File "/usr/local/lib/python2.7/dist-packages/celery/bin/__init__.py", line 2, in <module>
    from .base import Option
  File "/usr/local/lib/python2.7/dist-packages/celery/bin/base.py", line 16, in <module>
    from celery import VERSION_BANNER, Celery, maybe_patch_concurrency, signals
  File "/usr/local/lib/python2.7/dist-packages/celery/signals.py", line 16, in <module>
    from .utils.dispatch import Signal
  File "/usr/local/lib/python2.7/dist-packages/celery/utils/__init__.py", line 9, in <module>
    from .functional import memoize  # noqa
  File "/usr/local/lib/python2.7/dist-packages/celery/utils/functional.py", line 10, in <module>
    from kombu.utils.functional import (LRUCache, dictfilter, is_list, lazy,
  File "/usr/local/lib/python2.7/dist-packages/kombu/utils/__init__.py", line 5, in <module>
    from .compat import fileno, maybe_fileno, nested, register_after_fork
  File "/usr/local/lib/python2.7/dist-packages/kombu/utils/compat.py", line 14, in <module>
    import importlib_metadata
  File "/usr/local/lib/python2.7/dist-packages/importlib_metadata/__init__.py", line 16, in <module>
    from ._compat import (
  File "/usr/local/lib/python2.7/dist-packages/importlib_metadata/_compat.py", line 20, in <module>
    from backports.configparser import ConfigParser
ImportError: No module named backports.configparser</pre>

**Comment by jaraco** [comment]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on Mar 27, 2020, 23:56

The version of configparser released yesterday was 5.0.0, which dropped support for older Pythons, so it shouldn't have installed on Python 2.7.

Which version of configparser do you have installed and how did you install it?

Moreover, even if I create an environment with configparser 5 on Python 2.7, it works:

```
importlib_metadata master $ virtualenv --python python2.7 .tox/py27
created virtual environment CPython2.7.16.final.0-64 in 192ms
  creator CPython2macOsFramework(dest=/Users/jaraco/code/public/importlib_metadata/.tox/py27, clear=False, global=False)
  seeder FromAppData(download=False, pip=latest, setuptools=latest, wheel=latest, via=copy, app_data_dir=/Users/jaraco/Library/Application Support/virtualenv/seed-app-data/v1)
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator
importlib_metadata master $ .tox/py27/bin/pip install .                                                                                                                   
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Processing /Users/jaraco/code/public/importlib_metadata
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting zipp>=0.5
  Using cached zipp-1.2.0-py2.py3-none-any.whl (4.8 kB)
Collecting contextlib2; python_version < "3"
  Using cached contextlib2-0.6.0.post1-py2.py3-none-any.whl (9.8 kB)
Collecting configparser>=3.5; python_version < "3"
  Using cached configparser-4.0.2-py2.py3-none-any.whl (22 kB)
Collecting pathlib2; python_version < "3"
  Using cached pathlib2-2.3.5-py2.py3-none-any.whl (18 kB)
Processing /Users/jaraco/Library/Caches/pip/wheels/91/95/75/19c98a91239878abbc7c59970abd3b4e0438a7dd5b61778335/scandir-1.10.0-cp27-cp27m-macosx_10_14_x86_64.whl
Collecting six
  Using cached six-1.14.0-py2.py3-none-any.whl (10 kB)
Building wheels for collected packages: importlib-metadata
  Building wheel for importlib-metadata (PEP 517) ... done
  Created wheel for importlib-metadata: filename=importlib_metadata-1.5.2-py2.py3-none-any.whl size=30625 sha256=0f4a6b58297e0d30cb021e0e4cdedf483dbd5ed684ce538e1adfc69fdcb33c94
  Stored in directory: /private/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/pip-ephem-wheel-cache-9HHLRz/wheels/bd/f5/af/85d47ee091275eb2188c2a7b9c74d93c42320ffb1cb0badf92
Successfully built importlib-metadata
Installing collected packages: contextlib2, zipp, configparser, scandir, six, pathlib2, importlib-metadata
Successfully installed configparser-4.0.2 contextlib2-0.6.0.post1 importlib-metadata-1.5.2 pathlib2-2.3.5 scandir-1.10.0 six-1.14.0 zipp-1.2.0
importlib_metadata master $ .tox/py27/bin/pip install -U --ignore-requires-python configparser
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Processing /Users/jaraco/Library/Caches/pip/wheels/ed/19/df/7f9e0253f704f57c8481827309470f94101106180fbec77721/configparser-5.0.0-py2-none-any.whl
Installing collected packages: configparser
  Attempting uninstall: configparser
    Found existing installation: configparser 4.0.2
    Uninstalling configparser-4.0.2:
      Successfully uninstalled configparser-4.0.2
Successfully installed configparser-5.0.0
importlib_metadata master $ .tox/py27/bin/python -c "import importlib_metadata; print('done')"
done
```

Best I can tell, everything is working as intended. What do you think importlib_metadata or configparser can do here?

**Comment by jaraco** [comment]
In GitLab by [@splashcd](https://gitlab.com/splashcd) on Mar 28, 2020, 03:27

You've proved it works with 2.7, so I'm just going to pin the previous version of configparser.  Thank you for looking into this.  I appreciate your time and response.

**Comment by jaraco** [comment]
In GitLab by [@splashcd](https://gitlab.com/splashcd) on Mar 28, 2020, 03:27

closed
