### ISSUE TITLE
FastPath can raise UnicodeDecodeErrors on py2

### ISSUE THREAD

**Issue by jaraco** [python/importlib_metadata#121]
In GitLab by [@tburke](https://gitlab.com/tburke) on May 13, 2020, 07:35

importlib-metadata 1.6.0, python 2.7.17

With a directory named ☃ (`b'\xe2\x98\x83'`) in my current directory, I'd hit tracebacks ending like

```
  File ".../python2.7/site-packages/importlib_metadata/__init__.py", line 575, in entry_points
    ordered = sorted(eps, key=by_group)
  File ".../python2.7/site-packages/importlib_metadata/__init__.py", line 573, in <genexpr>
    dist.entry_points for dist in distributions())
  File ".../python2.7/site-packages/importlib_metadata/__init__.py", line 455, in search
    or n_low.startswith(name.prefix)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 0: ordinal not in range(128)
```

when running `flake8` for a project. Things work if I remove the directory (it was just for testing), but it'd be better to not have to do that.

**Comment by jaraco** [comment]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on Jun 5, 2020, 16:24

Indeed, I was able to replicate the error by simply creating such a directory and running the tests:

```
importlib_metadata master $ mkdir ☃
importlib_metadata master $ tox -e py27
py27 create: /Users/jaraco/code/public/importlib_metadata/.tox/py27
py27: pip_version is pip
py27 installdeps: pyfakefs
py27 develop-inst: /Users/jaraco/code/public/importlib_metadata
py27 installed: DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support,configparser==4.0.2,contextlib2==0.6.0.post1,-e git+gl://python-devs/importlib_metadata@ee3bed1cb0ad4a4fb1e5e549d3353595b99ee479#egg=importlib_metadata,importlib-resources==1.5.0,packaging==20.4,pathlib2==2.3.5,pyfakefs==3.7.2,pyparsing==2.4.7,scandir==1.10.0,singledispatch==3.4.0.3,six==1.15.0,typing==3.7.4.1,zipp==1.2.0
py27 run-test-pre: PYTHONHASHSEED='4034189629'
py27 run-test: commands[0] | python -m unittest discover
......E.importlib_metadata/__init__.py:454: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if (n_low in name.exact_matches
E....E.EE...E..............E..EE.EE.E..............
======================================================================
ERROR: test_zip_entry_points (importlib_metadata.tests.test_zip.TestEgg)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "importlib_metadata/tests/test_zip.py", line 41, in test_zip_entry_points
    scripts = dict(entry_points()['console_scripts'])
  File "importlib_metadata/__init__.py", line 575, in entry_points
    ordered = sorted(eps, key=by_group)
  File "importlib_metadata/__init__.py", line 573, in <genexpr>
    dist.entry_points for dist in distributions())
  File "importlib_metadata/__init__.py", line 455, in search
    or n_low.startswith(name.prefix)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 0: ordinal not in range(128)

======================================================================
ERROR: test_zip_version_does_not_match (importlib_metadata.tests.test_zip.TestEgg)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "importlib_metadata/tests/test_zip.py", line 38, in test_zip_version_does_not_match
    version('definitely-not-installed')
  File "importlib_metadata/__init__.py", line 564, in version
    return distribution(distribution_name).version
  File "importlib_metadata/__init__.py", line 537, in distribution
    return Distribution.from_name(distribution_name)
  File "importlib_metadata/__init__.py", line 201, in from_name
    dist = next(dists, None)
  File "importlib_metadata/__init__.py", line 455, in search
    or n_low.startswith(name.prefix)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 0: ordinal not in range(128)

======================================================================
ERROR: test_zip_entry_points (importlib_metadata.tests.test_zip.TestZip)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "importlib_metadata/tests/test_zip.py", line 41, in test_zip_entry_points
    scripts = dict(entry_points()['console_scripts'])
  File "importlib_metadata/__init__.py", line 575, in entry_points
    ordered = sorted(eps, key=by_group)
  File "importlib_metadata/__init__.py", line 573, in <genexpr>
    dist.entry_points for dist in distributions())
  File "importlib_metadata/__init__.py", line 455, in search
    or n_low.startswith(name.prefix)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 0: ordinal not in range(128)

======================================================================
ERROR: test_zip_version_does_not_match (importlib_metadata.tests.test_zip.TestZip)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "importlib_metadata/tests/test_zip.py", line 38, in test_zip_version_does_not_match
    version('definitely-not-installed')
  File "importlib_metadata/__init__.py", line 564, in version
    return distribution(distribution_name).version
  File "importlib_metadata/__init__.py", line 537, in distribution
    return Distribution.from_name(distribution_name)
  File "importlib_metadata/__init__.py", line 201, in from_name
    dist = next(dists, None)
  File "importlib_metadata/__init__.py", line 455, in search
    or n_low.startswith(name.prefix)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 0: ordinal not in range(128)

======================================================================
ERROR: test_entry_points (importlib_metadata.tests.test_api.APITests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "importlib_metadata/tests/test_api.py", line 57, in test_entry_points
    entries = dict(entry_points()['entries'])
  File "importlib_metadata/__init__.py", line 575, in entry_points
    ordered = sorted(eps, key=by_group)
  File "importlib_metadata/__init__.py", line 573, in <genexpr>
    dist.entry_points for dist in distributions())
  File "importlib_metadata/__init__.py", line 455, in search
    or n_low.startswith(name.prefix)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 0: ordinal not in range(128)

======================================================================
ERROR: test_for_name_does_not_exist (importlib_metadata.tests.test_api.APITests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "importlib_metadata/tests/test_api.py", line 42, in test_for_name_does_not_exist
    distribution('does-not-exist')
  File "importlib_metadata/__init__.py", line 537, in distribution
    return Distribution.from_name(distribution_name)
  File "importlib_metadata/__init__.py", line 201, in from_name
    dist = next(dists, None)
  File "importlib_metadata/__init__.py", line 455, in search
    or n_low.startswith(name.prefix)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 0: ordinal not in range(128)

======================================================================
ERROR: test_for_name_does_not_exist (importlib_metadata.tests.test_main.BasicTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "importlib_metadata/tests/test_main.py", line 36, in test_for_name_does_not_exist
    Distribution.from_name('does-not-exist')
  File "importlib_metadata/__init__.py", line 201, in from_name
    dist = next(dists, None)
  File "importlib_metadata/__init__.py", line 455, in search
    or n_low.startswith(name.prefix)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 0: ordinal not in range(128)

======================================================================
ERROR: test_egg (importlib_metadata.tests.test_main.DirectoryTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "importlib_metadata/tests/test_main.py", line 194, in test_egg
    version('foo')
  File "importlib_metadata/__init__.py", line 564, in version
    return distribution(distribution_name).version
  File "importlib_metadata/__init__.py", line 537, in distribution
    return Distribution.from_name(distribution_name)
  File "importlib_metadata/__init__.py", line 201, in from_name
    dist = next(dists, None)
  File "importlib_metadata/__init__.py", line 455, in search
    or n_low.startswith(name.prefix)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 0: ordinal not in range(128)

======================================================================
ERROR: test_egg_info (importlib_metadata.tests.test_main.DirectoryTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "importlib_metadata/tests/test_main.py", line 187, in test_egg_info
    version('unknown-package')
  File "importlib_metadata/__init__.py", line 564, in version
    return distribution(distribution_name).version
  File "importlib_metadata/__init__.py", line 537, in distribution
    return Distribution.from_name(distribution_name)
  File "importlib_metadata/__init__.py", line 201, in from_name
    dist = next(dists, None)
  File "importlib_metadata/__init__.py", line 455, in search
    or n_low.startswith(name.prefix)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 0: ordinal not in range(128)

======================================================================
ERROR: test_package_discovery (importlib_metadata.tests.test_main.DiscoveryTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "importlib_metadata/tests/test_main.py", line 162, in test_package_discovery
    dists = list(distributions())
  File "importlib_metadata/__init__.py", line 455, in search
    or n_low.startswith(name.prefix)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 0: ordinal not in range(128)

======================================================================
ERROR: test_entrypoint_with_colon_in_name (importlib_metadata.tests.test_main.ImportTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "importlib_metadata/tests/test_main.py", line 56, in test_entrypoint_with_colon_in_name
    entries = dict(entry_points()['entries'])
  File "importlib_metadata/__init__.py", line 575, in entry_points
    ordered = sorted(eps, key=by_group)
  File "importlib_metadata/__init__.py", line 573, in <genexpr>
    dist.entry_points for dist in distributions())
  File "importlib_metadata/__init__.py", line 455, in search
    or n_low.startswith(name.prefix)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 0: ordinal not in range(128)

======================================================================
ERROR: test_resolve (importlib_metadata.tests.test_main.ImportTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "importlib_metadata/tests/test_main.py", line 51, in test_resolve
    entries = dict(entry_points()['entries'])
  File "importlib_metadata/__init__.py", line 575, in entry_points
    ordered = sorted(eps, key=by_group)
  File "importlib_metadata/__init__.py", line 573, in <genexpr>
    dist.entry_points for dist in distributions())
  File "importlib_metadata/__init__.py", line 455, in search
    or n_low.startswith(name.prefix)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 0: ordinal not in range(128)

----------------------------------------------------------------------
Ran 59 tests in 0.185s

FAILED (errors=12)
ERROR: InvocationError for command /Users/jaraco/code/public/importlib_metadata/.tox/py27/bin/python -m unittest discover (exited with code 1)
_____________________________________________________________________ summary _____________________________________________________________________
ERROR:   py27: commands failed

```

Tests pass fine on Python 3, so I'm a little tempted to say the use-case is unsupported. If this issue were isolated to idiosyncratic cases such as just Linux, I'd definitely be inclined not to support it, but since it affects more pristine file systems such as those found on macOS and Windows, it would be nice to address it.

The `FastPath` class is a highly performance-optimized implementation, addressing performance issues reported in #95 and implemented in !103 and !106 and maybe others, so I'd be cautious about changes to it (although, the project does report benchmarks of performance with each submission, so a degradation in performance could be detected).

**Comment by jaraco** [comment]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on Jun 5, 2020, 16:25

I've dug a little deeper, and it seems the issue is that `sys.path` contains `bytes()` entries on Python 2. Casting the inputs to `FastPath` to Unicode seems to suppress the errors. Is that the right fix?

**Comment by jaraco** [comment]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on Jun 5, 2020, 16:49

mentioned in commit 76183b82abd590228b3883a027fcf2a7ae5a4ebf

**Comment by jaraco** [comment]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on Jun 5, 2020, 16:49

mentioned in commit fb8d5fe3ea7eb992458501969999c75797320846

**Comment by jaraco** [comment]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on Jun 5, 2020, 16:49

mentioned in commit b4f4f607f255e11ded393d758a0cc0bc9fbc9124

**Comment by jaraco** [comment]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on Jun 5, 2020, 17:39

closed via merge request !122

**Comment by jaraco** [comment]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on Jun 5, 2020, 17:39

mentioned in commit 95a187bc7a5fceacc4f2de75849f66440c45c5ac
