### ISSUE TITLE
Error raised: PackageNotFoundError

### ISSUE THREAD

**Issue by jaraco** [python/importlib_metadata#128]
In GitLab by [@TristanKnot](https://gitlab.com/TristanKnot) on Jul 8, 2020, 08:55

I recently received an error from the importlib_metadata when trying to use a program I'm working with. I'm not entirely sure how to resolve this and I thought this community would best understand why I'm receiving this error. 

I have g2p-seq2seq in my $PATH. 

Any idea why this error is being raised, and where I can look to resolve this? Please let me know if I can provide any additional info.

```
tek:g2p_seq2seq Tristan$ g2p-seq2seq
Traceback (most recent call last):
File "/Users/Tristan/anaconda3/bin/g2p-seq2seq", line 33, in
  sys.exit(load_entry_point('g2p-seq2seq==6.2.2a0', 'console_scripts', 'g2p-seq2seq')())
File "/Users/Tristan/anaconda3/bin/g2p-seq2seq", line 22, in importlib_load_entry_point
  for entry_point in distribution(dist_name).entry_points
File "/Users/Tristan/anaconda3/lib/python3.7/site-packages/importlib_metadata/api.py", line 310, in distribution
  return Distribution.from_name(package)
File "/Users/Tristan/anaconda3/lib/python3.7/site-packages/importlib_metadata/api.py", line 158, in from_name
  raise PackageNotFoundError(name)
importlib_metadata.api.PackageNotFoundError: g2p-seq2seq
```

**Comment by jaraco** [comment]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on Sep 22, 2020, 20:13

changed the description

**Comment by jaraco** [comment]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on Sep 22, 2020, 20:14

changed the description

**Comment by jaraco** [comment]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on Sep 22, 2020, 20:21

Hi Tristan. Sorry it's been so long for a response.

The issue is that the distribution package `g2p-seq2seq` doesn't have metadata on the `sys.path` (at least not in a form that importlib_metadata recognizes).

I would search for `*.egg-info` or `*.dist-info` in the directories indicated in `sys.path`. If you don't find it, that means your metadata is missing. If it's there, then the question is why doesn't importlib-metadata find it. If it's not there, the question is, how did you install that package that it did not get any metadata. Did you install with pip or something else?

Can you investigate further and see what you find?

The more detail you can provide about how you created this environment, the more helpful I can be.
