### ISSUE TITLE
importlib.metadata does not respect PYTHONPATH environment variable

### ISSUE THREAD

**Issue by jaraco** [python/importlib_metadata#132]
In GitLab by [@asavah](https://gitlab.com/asavah) on Oct 21, 2020, 19:56

This used to work with any random package using setuptools,
lets say I want install a dev version of meson into a separate prefix (folder) to avoid interfering with OS one.

```
PYTHONPATH=/my/prefix/lib/python3.8/site-packages python3 setup.py install --prefix=/my/prefix
PYTHONPATH=/my/prefix/lib/python3.8/site-packages /my/prefix/bin/meson
```

```
/my/prefix/lib/python3.8/site-packages# ls -1
easy-install.pth
meson-0.55.3-py3.8.egg
```

Now this fails
```
PYTHONPATH=/my/prefix/lib/python3.8/site-packages /my/prefix/bin/meson
Traceback (most recent call last):
  File "/my/prefix/bin/meson", line 33, in <module>
    sys.exit(load_entry_point('meson==0.55.3', 'console_scripts', 'meson')())
  File "/my/prefix/bin/meson", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.8/importlib/metadata.py", line 504, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.8/importlib/metadata.py", line 177, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: meson
```

OS: ubuntu 20.10, python 3.8.6

When making questionable "improvements" to something that existed and worked for years please make SURE you don't break expected behavior.

**Comment by jaraco** [comment]
In GitLab by [@asavah](https://gitlab.com/asavah) on Oct 21, 2020, 19:57

changed the description

**Comment by jaraco** [comment]
importlib_metadata does respect PYTHONPATH:

```
draft $ mkdir libs
draft $ pip install -t libs cowsay
Collecting cowsay
  Downloading cowsay-3.0-py2.py3-none-any.whl (19 kB)
Installing collected packages: cowsay
Successfully installed cowsay-3.0
draft $ env PYTHONPATH=libs pip-run -q importlib_metadata -- -c "import importlib_metadata; print(importlib_metadata.distribution('cowsay
').entry_points)"
[EntryPoint(name='cowsay', value='cowsay.main:cli', group='console_scripts')]
```

Your issue probably lies in how `setup.py install` generates and installs (or fails to install) metadata.

I would inspect that prefix where you've installed the package and confirm that the metadata (egg-info/dist-info) exists.

I'm closing this issue as invalid, although you're welcome to follow up with more information. One comment though:



> When making questionable "improvements" to something that existed and worked for years please make SURE you don't break expected behavior.

Hostile messages like these (characterizing the effort as "questionable", putting _improvements_ in quotes, and demanding perfect stability) are not received well by the volunteers that make this work happen. Please review the [Python Code of Conduct](https://www.python.org/psf/conduct/) and consider adjusting your attitude before re-engaging on this issue. Although possibly not clearly advertised, this project falls under that code of conduct. Thanks for your consideration.
