### ISSUE TITLE
KeyError when importlib_metadata is loaded as an egg

### ISSUE THREAD

**Issue by jaraco** [python/importlib_metadata#19]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on Oct 15, 2018, 10:20

In [this job](https://travis-ci.org/yougov/mongo-connector/jobs/440958423), you can see the introduction of `import importlib_metadata` to a project that uses `setup.py test` will result in an exception:

```
running egg_info
creating mongo_connector.egg-info
writing mongo_connector.egg-info/PKG-INFO
writing entry points to mongo_connector.egg-info/entry_points.txt
writing requirements to mongo_connector.egg-info/requires.txt
writing dependency_links to mongo_connector.egg-info/dependency_links.txt
writing top-level names to mongo_connector.egg-info/top_level.txt
writing manifest file 'mongo_connector.egg-info/SOURCES.txt'
reading manifest file 'mongo_connector.egg-info/SOURCES.txt'
writing manifest file 'mongo_connector.egg-info/SOURCES.txt'
running build_ext
Traceback (most recent call last):
  File "setup.py", line 140, in <module>
    **extra_opts
  File "/opt/python/3.4.6/lib/python3.4/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/opt/python/3.4.6/lib/python3.4/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/opt/python/3.4.6/lib/python3.4/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/travis/virtualenv/python3.4.6/lib/python3.4/site-packages/setuptools/command/test.py", line 211, in run
    self.run_tests()
  File "/home/travis/virtualenv/python3.4.6/lib/python3.4/site-packages/setuptools/command/test.py", line 234, in run_tests
    **exit_kwarg
  File "/opt/python/3.4.6/lib/python3.4/unittest/main.py", line 92, in __init__
    self.parseArgs(argv)
  File "/opt/python/3.4.6/lib/python3.4/unittest/main.py", line 139, in parseArgs
    self.createTests()
  File "/opt/python/3.4.6/lib/python3.4/unittest/main.py", line 146, in createTests
    self.module)
  File "/opt/python/3.4.6/lib/python3.4/unittest/loader.py", line 157, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/opt/python/3.4.6/lib/python3.4/unittest/loader.py", line 157, in <listcomp>
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/opt/python/3.4.6/lib/python3.4/unittest/loader.py", line 128, in loadTestsFromName
    return self.loadTestsFromModule(obj)
  File "/home/travis/virtualenv/python3.4.6/lib/python3.4/site-packages/setuptools/command/test.py", line 43, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/opt/python/3.4.6/lib/python3.4/unittest/loader.py", line 116, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
  File "/home/travis/build/yougov/mongo-connector/tests/test_command_replication.py", line 26, in <module>
    from mongo_connector.doc_managers.doc_manager_base import DocManagerBase
  File "/home/travis/build/yougov/mongo-connector/mongo_connector/doc_managers/doc_manager_base.py", line 19, in <module>
    from mongo_connector.connector import get_mininum_mongodb_version
  File "/home/travis/build/yougov/mongo-connector/mongo_connector/connector.py", line 34, in <module>
    from mongo_connector import config, constants, errors, util
  File "/home/travis/build/yougov/mongo-connector/mongo_connector/config.py", line 20, in <module>
    from mongo_connector.constants import __version__
  File "/home/travis/build/yougov/mongo-connector/mongo_connector/constants.py", line 16, in <module>
    import importlib_metadata
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "/home/travis/build/yougov/mongo-connector/.eggs/importlib_metadata-0.6-py3.4.egg/importlib_metadata/__init__.py", line 17, in <module>
  File "/home/travis/build/yougov/mongo-connector/.eggs/importlib_metadata-0.6-py3.4.egg/importlib_metadata/api.py", line 105, in version
  File "/home/travis/build/yougov/mongo-connector/.eggs/importlib_metadata-0.6-py3.4.egg/importlib_metadata/api.py", line 86, in distribution
  File "/home/travis/build/yougov/mongo-connector/.eggs/importlib_metadata-0.6-py3.4.egg/importlib_metadata/api.py", line 48, in from_name
  File "/home/travis/build/yougov/mongo-connector/.eggs/importlib_metadata-0.6-py3.4.egg/importlib_metadata/_hooks.py", line 126, in find_distribution
  File "/opt/python/3.4.6/lib/python3.4/zipfile.py", line 1084, in getinfo
    'There is no item named %r in the archive' % name)
KeyError: "There is no item named 'importlib_metadata-0.6.dist-info/METADATA' in the archive"
The command "python setup.py test" exited with 1.
```

**Comment by jaraco** [comment]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on Oct 15, 2018, 10:28

I believe this project has an express interest not to support eggs, but this use-case is pretty compelling - any project that does not carefully avoid allowing `setuptools` to install packages will end up with `importlib_metadata` being installed as an egg and it will fail to load its own metadata.

I see a few options:

- Add support for loading egg-info from eggs.
- Suppress the error if `importlib_metadata` is unable to load its own metadata. This approach may also benefit the port to Python 3.8, which may also not have the necessary metadata.
- Declare non-support for this use-case - force projects that wish to use importlib_metadata to always install it with pip. To this end, maybe importlib_metadata should disallow being built as an egg (disable the command in setup.py).

@warsaw Do you have any opinion on the matter?

**Comment by jaraco** [comment]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on Oct 29, 2018, 21:10

Good news. At least for the mongo-connector job above, I found that after converting the project to run its tests under tox instead of using `setup.py test`, the error goes away.

So that at least reinforces that there is a viable alternative (avoid easy_install at all costs).

I'm now leaning toward suppressing the error in `importlib_metadata`. My main reluctance is around the precedent that sets.

**Comment by jaraco** [comment]
In GitLab by [@warsaw](https://gitlab.com/warsaw) on Nov 2, 2018, 24:37

How common is `setup.py test` these days?  I used to use it quite a bit, but of course now I use `tox` everywhere.  Also, are there any other conditions which could cause the package to install `egg-info` instead of `dist-info`?  Maybe there are more common use cases that we should be supporting?

How hard do you think it would be to support loading egg-info from eggs?

I think I'm leaning toward, none of these use cases are common enough to be worth supporting.

**Comment by jaraco** [comment]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on Nov 2, 2018, 24:50

`setup.py test` is pretty common, and about equally (if I had to guess) `setup.py pytest` (using [pytest-runner](https://pypi.org/project/pytest-runner)).

I was thinking that other distutils commands might have a similar issue - if they end up installing the `install_requires` (as `setup.py test` does) or if they specify `importlib_metadata` in their `setup_requires`.

I should have mentioned about the options above:

- The first option provides first-class support with no downsides short of maintaining the code.
- The second option doesn't provide support for metadata in zip eggs, but does at least prevent importlib_metadata from crashing if it was installed that way.
- The third option just crashes as things do now, or maybe earlier and with a nicer message.

The precedent I was afraid of setting was that of having a conditional wrapper around the invocation of importlib_metadata on itself... which other packages might also do if importlib_metadata does that. Yeah, as I think about it more, other packages would have the same issue, so bypassing the error in importlib_metadata would only kick the can down the road a bit... and demand that other packages trap the same error.

I'm now on the same page as you, that maybe the use cases are not common enough, and the recommendation can be to run tox (or otherwise use tools that build everything with pip).

Therefore, I'm closing the ticket, but happy to resume the conversation if others arrive here and find that the recommendation is cost-prohibitive or otherwise not suitable, or there's more that importlib_metadata can do (simply) to help accommodate the situation.

**Comment by jaraco** [comment]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on Nov 2, 2018, 24:50

closed

**Comment by jaraco** [comment]
In GitLab by [@warsaw](https://gitlab.com/warsaw) on Nov 2, 2018, 24:54

+1

Would you be able to write up a very quick documentation MR with some appropriate language and warnings?

**Comment by jaraco** [comment]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on Nov 2, 2018, 01:04

reopened

**Comment by jaraco** [comment]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on Nov 2, 2018, 01:04

assigned to @jaraco

**Comment by jaraco** [comment]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on Nov 2, 2018, 01:04

Yes.

**Comment by jaraco** [comment]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on Nov 2, 2018, 02:00

mentioned in commit 52199abdc5421c81a710a605f0d236d52af0bd6f

**Comment by jaraco** [comment]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on Nov 2, 2018, 20:16

closed via merge request !25

**Comment by jaraco** [comment]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on Nov 2, 2018, 20:16

closed via commit 52199abdc5421c81a710a605f0d236d52af0bd6f

**Comment by jaraco** [comment]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on Nov 2, 2018, 20:16

mentioned in commit 9df4a0fdb8d8efe01fd46928f4d424894cb4639f

**Comment by jaraco** [comment]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on May 14, 2019, 13:23

mentioned in merge request !65
