### ISSUE TITLE
Distribution lookup fails with dashes in the name

### ISSUE THREAD

**Issue by jaraco** [python/importlib_metadata#21]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on Nov 4, 2018, 09:36

Similar to #20, I've found that if a package has dashes in the name, the distribution lookup will fail with a `PackageNotFoundError`.

```
>>> import importlib_metadata
>>> importlib_metadata.version('elastic2-doc-manager')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jaraco/code/yg/public/elastic2-doc-manager/.tox/python/lib/python3.7/site-packages/importlib_metadata/api.py", line 105, in version
    return distribution(package).version
  File "/Users/jaraco/code/yg/public/elastic2-doc-manager/.tox/python/lib/python3.7/site-packages/importlib_metadata/api.py", line 86, in distribution
    return Distribution.from_name(package)
  File "/Users/jaraco/code/yg/public/elastic2-doc-manager/.tox/python/lib/python3.7/site-packages/importlib_metadata/api.py", line 52, in from_name
    raise PackageNotFoundError(name)
importlib_metadata.api.PackageNotFoundError: elastic2-doc-manager
>>> ^D
elastic2-doc-manager feature/auto-version $ ls -d .tox/python/lib/python3.7/site-packages/elastic*.dist-info
.tox/python/lib/python3.7/site-packages/elastic2_doc_manager-0.4.1.dev4+g5558283.dist-info
```

I suspect that to support resolving version numbers from filenames and disambiguating a dash in the name from the dash that separates the name from the version, some tool is "normalizing" dashes to underscores... so to look up the metadata for a distribution, the name needs to be normalized this way.

I might have thought it would go the other way, because pypi [normalizes the other way](https://pypi.org/project/elastic2_doc_manager/).

**Comment by jaraco** [comment]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on Nov 4, 2018, 18:09

mentioned in commit 6bdc0add510756b8319266591a3350937c9bbecd

**Comment by jaraco** [comment]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on Nov 4, 2018, 18:11

I'm considering this issue much more severe than that of #20, because in #20, the workaround is to use the name in the same case as was used in the package declaration. But in this one, the user is required to use a mangled version of the name, which would be preferable to avoid.

**Comment by jaraco** [comment]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on Nov 4, 2018, 18:37

mentioned in commit 2981247ca602dffe6759a6ad1ef94182e5c4045a

**Comment by jaraco** [comment]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on Nov 4, 2018, 18:37

mentioned in commit 0414c6f4f98522145fc7180fadd153642ed69606

**Comment by jaraco** [comment]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on Nov 4, 2018, 18:49

mentioned in merge request !26

**Comment by jaraco** [comment]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on Nov 27, 2018, 17:18

closed via merge request !26
