### ISSUE TITLE
Diffcov failing since migration to Github Actions

### ISSUE THREAD

**Issue by jaraco** [python/importlib_metadata#257]
Diffcov tests are failing thus:

```
diffcov run-test: commands[2] | python -m coverage combine --rcfile=/home/runner/work/importlib_metadata/importlib_metadata/coverage.ini
diffcov run-test: commands[3] | python -m coverage xml --rcfile=/home/runner/work/importlib_metadata/importlib_metadata/coverage.ini
diffcov run-test: commands[4] | diff-cover coverage.xml --html-report diffcov.html
Traceback (most recent call last):
  File "/home/runner/work/importlib_metadata/importlib_metadata/.tox/diffcov/bin/diff-cover", line 8, in <module>
    sys.exit(main())
  File "/home/runner/work/importlib_metadata/importlib_metadata/.tox/diffcov/lib/python3.9/site-packages/diff_cover/diff_cover_tool.py", line 216, in main
    percent_covered = generate_coverage_report(
  File "/home/runner/work/importlib_metadata/importlib_metadata/.tox/diffcov/lib/python3.9/site-packages/diff_cover/diff_cover_tool.py", line 184, in generate_coverage_report
    reporter.generate_report(output_file)
  File "/home/runner/work/importlib_metadata/importlib_metadata/.tox/diffcov/lib/python3.9/site-packages/diff_cover/report_generator.py", line 251, in generate_report
    report = template.render(self._context())
  File "/home/runner/work/importlib_metadata/importlib_metadata/.tox/diffcov/lib/python3.9/site-packages/diff_cover/report_generator.py", line 300, in _context
    context = super().report_dict()
  File "/home/runner/work/importlib_metadata/importlib_metadata/.tox/diffcov/lib/python3.9/site-packages/diff_cover/report_generator.py", line 183, in report_dict
    src_stats = {src: self._src_path_stats(src) for src in self.src_paths()}
  File "/home/runner/work/importlib_metadata/importlib_metadata/.tox/diffcov/lib/python3.9/site-packages/diff_cover/report_generator.py", line 85, in src_paths
    for src, summary in self._diff_violations().items()
  File "/home/runner/work/importlib_metadata/importlib_metadata/.tox/diffcov/lib/python3.9/site-packages/diff_cover/report_generator.py", line 178, in _diff_violations
    for src_path in self._diff.src_paths_changed()
  File "/home/runner/work/importlib_metadata/importlib_metadata/.tox/diffcov/lib/python3.9/site-packages/diff_cover/diff_reporter.py", line 151, in src_paths_changed
    diff_dict = self._git_diff()
  File "/home/runner/work/importlib_metadata/importlib_metadata/.tox/diffcov/lib/python3.9/site-packages/diff_cover/diff_reporter.py", line 200, in _git_diff
    for diff_str in self._get_included_diff_results():
  File "/home/runner/work/importlib_metadata/importlib_metadata/.tox/diffcov/lib/python3.9/site-packages/diff_cover/diff_reporter.py", line 173, in _get_included_diff_results
    included = [self._git_diff_tool.diff_committed(self._compare_branch)]
  File "/home/runner/work/importlib_metadata/importlib_metadata/.tox/diffcov/lib/python3.9/site-packages/diff_cover/git_diff.py", line 66, in diff_committed
    return execute(self._default_git_args + self._default_diff_args + [diff_range])[
  File "/home/runner/work/importlib_metadata/importlib_metadata/.tox/diffcov/lib/python3.9/site-packages/diff_cover/command_runner.py", line 45, in execute
    raise CommandError(stderr)
diff_cover.command_runner.CommandError: fatal: ambiguous argument 'origin/master...HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

ERROR: InvocationError for command /home/runner/work/importlib_metadata/importlib_metadata/.tox/diffcov/bin/diff-cover coverage.xml --html-report diffcov.html (exited with code 1)
___________________________________ summary ____________________________________
ERROR:   diffcov: commands failed
```

**Comment by jaraco** [comment]
Fixed in #252.
