### ISSUE TITLE
Missing typing typing_extensions dependency on Python < 3.8?

### ISSUE THREAD

**Issue by krassowski** [python/importlib_metadata#270]
Today our builds started failing due to missing `typing_extensions` dependency for `importlib_metadata`:

```python
Traceback (most recent call last):
  File "/usr/share/miniconda/envs/jupyterlab-lsp/lib/python3.6/site-packages/jsonschema/__init__.py", line 31, in <module>
    from importlib import metadata
ImportError: cannot import name 'metadata'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/miniconda/envs/jupyterlab-lsp/lib/python3.6/site-packages/importlib_metadata/_compat.py", line 8, in <module>
    from typing import Protocol
ImportError: cannot import name 'Protocol'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/miniconda/envs/jupyterlab-lsp/lib/python3.6/site-packages/jupyterlab_server/server.py", line 20, in <module>
    from notebook.notebookapp import aliases, flags, NotebookApp as ServerApp
  File "/usr/share/miniconda/envs/jupyterlab-lsp/lib/python3.6/site-packages/notebook/notebookapp.py", line 85, in <module>
    from .services.contents.manager import ContentsManager
  File "/usr/share/miniconda/envs/jupyterlab-lsp/lib/python3.6/site-packages/notebook/services/contents/manager.py", line 17, in <module>
    from nbformat import sign, validate as validate_nb, ValidationError
  File "/usr/share/miniconda/envs/jupyterlab-lsp/lib/python3.6/site-packages/nbformat/__init__.py", line 32, in <module>
    from .validator import validate, ValidationError
  File "/usr/share/miniconda/envs/jupyterlab-lsp/lib/python3.6/site-packages/nbformat/validator.py", line 12, in <module>
    from .json_compat import get_current_validator, ValidationError
  File "/usr/share/miniconda/envs/jupyterlab-lsp/lib/python3.6/site-packages/nbformat/json_compat.py", line 10, in <module>
    import jsonschema
  File "/usr/share/miniconda/envs/jupyterlab-lsp/lib/python3.6/site-packages/jsonschema/__init__.py", line 33, in <module>
    import importlib_metadata as metadata
  File "/usr/share/miniconda/envs/jupyterlab-lsp/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 15, in <module>
    from ._compat import (
  File "/usr/share/miniconda/envs/jupyterlab-lsp/lib/python3.6/site-packages/importlib_metadata/_compat.py", line 15, in <module>
    from typing_extensions import Protocol  # type: ignore
ModuleNotFoundError: No module named 'typing_extensions'
```

See https://github.com/krassowski/jupyterlab-lsp/issues/426. Could it be some change in `importlib_metadata` setup configuration that causes this issue, or is this the responsibility of other packages importing `importlib_metadata` (here `jupyterlab_server` imports `jsonschema` which imports `importlib_metadata`) to ensure `typing_extensions` are available on onlder Python installations? I think it should be addressed here but please correct me if I am wrong.

**Comment by krassowski** [comment]
It might be specific to conda-forge build that we use, it seems that there was a glitch and I do not know if it was solved or not (https://github.com/conda-forge/importlib_metadata-feedstock/issues/53)

**Comment by krassowski** [comment]
Closing as it appears to be a problem with the conda packaging only. Follow ups: 
- https://github.com/conda-forge/importlib_metadata-feedstock/pull/55
- https://github.com/conda-forge/importlib_metadata-feedstock/issues/57

**Comment by BlackBo6** [comment]
is any one solved this problem
