### ISSUE TITLE
flufl.flake8 failing with TypeError

### ISSUE THREAD

**Issue by jaraco** [python/importlib_metadata#31]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on Dec 5, 2018, 19:36

I've added a few commits to master as a basis for #29 (4434eaa, 78bc056, and c546d9d), and now the qa tests are crashing:

```
importlib_metadata master $ tox -e qa -r
qa recreate: /Users/jaraco/code/public/importlib_metadata/.tox/qa
qa installdeps: mypy, flake8, flufl.flake8
qa develop-inst: /Users/jaraco/code/public/importlib_metadata
qa installed: You are using pip version 10.0.1, however version 18.1 is available.,You should consider upgrading via the 'pip install --upgrade pip' command.,flake8==3.6.0,flufl.flake8==0.9,-e git+gl://python-devs/importlib_metadata@c546d9d40cb3eea26fe6939b33f8271f25d685be#egg=importlib_metadata,mccabe==0.6.1,mypy==0.641,mypy-extensions==0.4.1,pycodestyle==2.4.0,pyflakes==2.0.0,typed-ast==1.1.0
qa run-test-pre: PYTHONHASHSEED='1556744124'
qa runtests: commands[0] | python -m flake8 importlib_metadata
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/jaraco/code/public/importlib_metadata/.tox/qa/lib/python3.7/site-packages/flake8/__main__.py", line 4, in <module>
    cli.main()
  File "/Users/jaraco/code/public/importlib_metadata/.tox/qa/lib/python3.7/site-packages/flake8/main/cli.py", line 16, in main
    app.run(argv)
  File "/Users/jaraco/code/public/importlib_metadata/.tox/qa/lib/python3.7/site-packages/flake8/main/application.py", line 412, in run
    self._run(argv)
  File "/Users/jaraco/code/public/importlib_metadata/.tox/qa/lib/python3.7/site-packages/flake8/main/application.py", line 400, in _run
    self.run_checks()
  File "/Users/jaraco/code/public/importlib_metadata/.tox/qa/lib/python3.7/site-packages/flake8/main/application.py", line 318, in run_checks
    self.file_checker_manager.run()
  File "/Users/jaraco/code/public/importlib_metadata/.tox/qa/lib/python3.7/site-packages/flake8/checker.py", line 340, in run
    self.run_serial()
  File "/Users/jaraco/code/public/importlib_metadata/.tox/qa/lib/python3.7/site-packages/flake8/checker.py", line 324, in run_serial
    checker.run_checks()
  File "/Users/jaraco/code/public/importlib_metadata/.tox/qa/lib/python3.7/site-packages/flake8/checker.py", line 612, in run_checks
    self.run_ast_checks()
  File "/Users/jaraco/code/public/importlib_metadata/.tox/qa/lib/python3.7/site-packages/flake8/checker.py", line 520, in run_ast_checks
    for (line_number, offset, text, check) in runner:
  File "/Users/jaraco/code/public/importlib_metadata/.tox/qa/lib/python3.7/site-packages/flufl/flake8/imports.py", line 141, in run
    if last_import.module > record.module:
TypeError: '>' not supported between instances of 'str' and 'NoneType'
ERROR: InvocationError for command '/Users/jaraco/code/public/importlib_metadata/.tox/qa/bin/python -m flake8 importlib_metadata' (exited with code 1)
```

I suspect an issue in flufl.flake8.

**Comment by jaraco** [comment]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on Dec 5, 2018, 19:41

When the crash happens: 

```
(Pdb) self.filename
'importlib_metadata/tests/test_main.py'
(Pdb) record
ImportRecord(itype=<ImportType.from_import: 1>, lineno=9, colno=0, module=None, names=['fixtures'])
```

It seems flufl.flake8 doesn't support `from` imports such as:

```
from . import fixtures
```

**Comment by jaraco** [comment]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on Dec 5, 2018, 19:43

I tried adding `# noqa` to that line, but it doesn't appear to be honored.

**Comment by jaraco** [comment]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on Dec 5, 2018, 19:44

mentioned in commit e6d7a06e9bc321b7a1e540119c3275ba5304b747

**Comment by jaraco** [comment]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on Dec 5, 2018, 19:48

The workaround in e6d7a06e should suffice to bypass the issue until it's addressed upstream.

**Comment by jaraco** [comment]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on Dec 5, 2018, 19:48

closed
