### ISSUE TITLE
[Django/Python] ImportError: cannot import name 'TypeVarTuple' from 'typing_extensions' 

### ISSUE THREAD

**Issue by soype** [python/importlib_metadata#318]
Hi all! I'm sort of new to Django and Python. I've been working on my macbook with little to no problems using Django 3.2.3 (I think) and Python 3.4. 

I've moved to my iMac and decided to install Django and Python, and continue my studies from there. I pip installed the latest Django and Python and tried to run a new project. I did some adjustments to my settings.py project and I suddenly get this error which doesn't seem to be related to my typing (but maybe it is?).

I've never had this error before and as I googled it I found some issues with people actually trying to import typing extensions, but not my case. Should I do a reinstall of Python and Django or am I missing something here?

Thanks!

```
estudio@iMac new_blog % python3 manage.py runserver
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/django/core/management/commands/runserver.py", line 110, in inner_run
    autoreload.raise_last_exception()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/django/utils/autoreload.py", line 87, in raise_last_exception
    raise _exception[1]
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/django/core/management/__init__.py", line 375, in execute
    autoreload.check_errors(django.setup)()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/django/apps/config.py", line 301, in import_models
    self.models_module = import_module(models_module_name)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/estudio/Documents/Django_projects/new_blog/blog/models.py", line 1, in <module>
    from typing_extensions import TypeVarTuple
ImportError: cannot import name 'TypeVarTuple' from 'typing_extensions' (/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/typing_extensions.py)

```

**Comment by jaraco** [comment]
The traceback you have appears to be unrelated to `importlib_metadata` (only one part of the `importlib` package).

The issue appears to be that your project (new_blog) was generated with an older version of Python and Django and so isn't compatible with the latest version of Python/Django/typing-extensions, as the current version of typing_extensions no longer has the `TypeVarTuple` class.

I recommend to take your issue to a Django group for support. Alternatively, consider just generating a new Django project using your new environment and see if you can ascertain what changes you need to make to your models to make them compatible with the latest Django version.

Good luck.
