### ISSUE TITLE
KeyError on import - There is no item named 'importlib_metadata-0.6.dist-info/METADATA' in the archive

### ISSUE THREAD

**Issue by jaraco** [python/importlib_metadata#32]
In GitLab by [@fizwit](https://gitlab.com/fizwit) on Dec 5, 2018, 22:01

built importlib_metadata from source and it fails to run.

```
$ python
Python 3.6.7 (default, Dec  5 2018, 09:25:16)
[GCC 5.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import importlib_metadata
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/app/easybuild/software/Python/3.6.7-foss-2016b-fh1/lib/python3.6/site-packages/importlib_metadata-0.6-py3.6.egg/importlib_metadata/__init__.py", line 17, in <module>
  File "/app/easybuild/software/Python/3.6.7-foss-2016b-fh1/lib/python3.6/site-packages/importlib_metadata-0.6-py3.6.egg/importlib_metadata/api.py", line 105, in version
  File "/app/easybuild/software/Python/3.6.7-foss-2016b-fh1/lib/python3.6/site-packages/importlib_metadata-0.6-py3.6.egg/importlib_metadata/api.py", line 86, in distribution
  File "/app/easybuild/software/Python/3.6.7-foss-2016b-fh1/lib/python3.6/site-packages/importlib_metadata-0.6-py3.6.egg/importlib_metadata/api.py", line 48, in from_name
  File "/app/easybuild/software/Python/3.6.7-foss-2016b-fh1/lib/python3.6/site-packages/importlib_metadata-0.6-py3.6.egg/importlib_metadata/_hooks.py", line 126, in find_distribution
  File "/app/easybuild/software/Python/3.6.7-foss-2016b-fh1/lib/python3.6/zipfile.py", line 1304, ingetinfo
    'There is no item named %r in the archive' % name)
KeyError: "There is no item named 'importlib_metadata-0.6.dist-info/METADATA' in the archive"
```

**Comment by jaraco** [comment]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on Dec 6, 2018, 03:13

changed the description

**Comment by jaraco** [comment]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on Dec 6, 2018, 03:20

importlib_metadata doesn't support loading metadata from eggs, and importlib_metadata requires its own metadata on import, so importlib_metadata is unusable if installed as an egg.

To avoid installing importlib_metadata as an egg, always install using pip. Will that satisfy your needs? If not, can you elaborate on your use-case?

**Comment by jaraco** [comment]
In GitLab by [@fizwit](https://gitlab.com/fizwit) on Dec 6, 2018, 04:34

I've been using pip for installing importlib-metadata. I switched from version 0.6 to 0.7 and now it loads without error.

**Comment by jaraco** [comment]
In GitLab by [@fizwit](https://gitlab.com/fizwit) on Dec 6, 2018, 04:34

closed

**Comment by jaraco** [comment]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on Dec 6, 2018, 10:32

changed title from **{-import importlib_metadata fails-}** to **{+KeyError on import - There is no item named 'importlib_metadata-0.6.dist-info/METADATA' in the archive+}**
