### ISSUE TITLE
4.3.0 bug from pluggy dependency

### ISSUE THREAD

**Issue by ezloj** [python/importlib_metadata#321]
Discovered after installing the `awsume` tool:
awsume
```
Traceback (most recent call last):
  File "/usr/local/bin/awsumepy", line 7, in <module>
    from awsume.awsumepy.main import main
  File "/usr/local/lib/python3.5/dist-packages/awsume/awsumepy/__init__.py", line 1, in <module>
    from . import app
  File "/usr/local/lib/python3.5/dist-packages/awsume/awsumepy/app.py", line 7, in <module>
    import pluggy
  File "/usr/local/lib/python3.5/dist-packages/pluggy/__init__.py", line 16, in <module>
    from .manager import PluginManager, PluginValidationError
  File "/usr/local/lib/python3.5/dist-packages/pluggy/manager.py", line 11, in <module>
    import importlib_metadata
  File "/usr/local/lib/python3.5/dist-packages/importlib_metadata/__init__.py", line 55
    return f"No package metadata was found for {self.name}"
                                                          ^

SyntaxError: invalid syntax
```

**Comment by jaraco** [comment]
importlib_metadata 3.0 dropped support for Python 3.5. If you use a recent version of pip to install importlib_metadata, it will only install `importlib_metadata < 3` - or you can pin that version in your application.

**Comment by ezloj** [comment]
Oh, thank you for explanation and sorry for confusion.
