### ISSUE TITLE
#339 / v4.8.0 broke stevedore which broke bandit, openstackclient, flake8 and others

### ISSUE THREAD

**Issue by mr-c** [python/importlib_metadata#348]
Hello, #339 in v4.8.0  broke `stevedore` which broke `bandit` for at least myself (but probably others)

https://github.com/common-workflow-language/cwltool/pull/1482/checks?check_run_id=3454232416#step:9:50
https://github.com/PyCQA/bandit/issues/730

Reverting to `importlib_metadata` version 4.7.1 resolves the problem for me

_Originally posted by @mr-c in https://github.com/python/importlib_metadata/issues/339#issuecomment-907764540_

**Comment by Stannislav** [comment]
Same
```
$ bandit
Traceback (most recent call last):
  File "/Users/me/project/.tox/lint/lib/python3.7/site-packages/stevedore/_cache.py", line 159, in _get_data_for_path
    with open(filename, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/sschmidt/Library/Caches/Python Entry Points/f02c0770d01da06fbfcfe6435c8feb2e12f0e5fb7e239f6cf91d4d8d088821d8'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/me/project/.tox/lint/bin/bandit", line 5, in <module>
    from bandit.cli.main import main
  File "/Users/me/project/.tox/lint/lib/python3.7/site-packages/bandit/__init__.py", line 19, in <module>
    from bandit.core import config  # noqa
  File "/Users/me/project/.tox/lint/lib/python3.7/site-packages/bandit/core/__init__.py", line 17, in <module>
    from bandit.core import config  # noqa
  File "/Users/me/project/.tox/lint/lib/python3.7/site-packages/bandit/core/config.py", line 12, in <module>
    from bandit.core import extension_loader
  File "/Users/me/project/.tox/lint/lib/python3.7/site-packages/bandit/core/extension_loader.py", line 109, in <module>
    MANAGER = Manager()
  File "/Users/me/project/.tox/lint/lib/python3.7/site-packages/bandit/core/extension_loader.py", line 25, in __init__
    self.load_formatters(formatters_namespace)
  File "/Users/me/project/.tox/lint/lib/python3.7/site-packages/bandit/core/extension_loader.py", line 33, in load_formatters
    verify_requirements=False,
  File "/Users/me/project/.tox/lint/lib/python3.7/site-packages/stevedore/extension.py", line 136, in __init__
    verify_requirements)
  File "/Users/me/project/.tox/lint/lib/python3.7/site-packages/stevedore/extension.py", line 218, in _load_plugins
    for ep in self.list_entry_points():
  File "/Users/me/project/.tox/lint/lib/python3.7/site-packages/stevedore/extension.py", line 207, in list_entry_points
    eps = list(_cache.get_group_all(self.namespace))
  File "/Users/me/project/.tox/lint/lib/python3.7/site-packages/stevedore/_cache.py", line 179, in get_group_all
    data = self._get_data_for_path(path)
  File "/Users/me/project/.tox/lint/lib/python3.7/site-packages/stevedore/_cache.py", line 162, in _get_data_for_path
    data = _build_cacheable_data(path)
  File "/Users/me/project/.tox/lint/lib/python3.7/site-packages/stevedore/_cache.py", line 119, in _build_cacheable_data
    item = ep[:]  # convert namedtuple to tuple
TypeError: 'EntryPoint' object is not subscriptable
```

**Comment by freedge** [comment]
Seems to break openstack cli and rally testing as well. Opening https://storyboard.openstack.org/#!/story/2009151

**Comment by WilliamDEdwards** [comment]
Same here with flake8.

**Comment by jaraco** [comment]
Sorry for the inconvenience. I've yanked 4.8.0.

**Comment by jaraco** [comment]
I'd like devise a way to capture these requirements. I can see from the failure that stevedore is expecting `__getitem__(slice)` to return a tuple, something that `namedtuple` (or other tuple) would do implicitly.

**Comment by jaraco** [comment]
@mtreinish: You may wish to refrain from pinning too many projects as I've yanked the offending version and expect to release the next version without the broken behavior.

**Comment by mr-c** [comment]
> Sorry for the inconvenience. I've yanked 4.8.0 while working out a remedy.

Thanks for the quick yank! I know this isn't nice news to receive.

**Comment by jaraco** [comment]
In #349, I've drafted a fix but marking the access by item as deprecated. I can add other missing but expected tuple behaviors there as well if needed. I welcome feedback.

**Comment by jaraco** [comment]
v4.8.1 is releasing now. I believe this addresses the issue. It's possible there are other usages out there dependent on tuple behaviors. If so, please raise an issue, mention me, and I'll address those promptly.

**Comment by jacwalte** [comment]
Looks like this issue has been reintroduced in v5.0.0.

We are seeing all pipelines fail this morning with the same message when using bandit for security linting.

![image](https://user-images.githubusercontent.com/58958666/193653445-f6866c7f-e1a0-4eab-9607-58208e331a95.png)

**Comment by jaraco** [comment]
I'm not confident of the report above for a couple of reasons.

First, the report doesn't include the actual error message. It includes a screenshot with only a `FileNotFoundError`.

Second, the issue reported above was addressed in 4.8.1, but the changes made in the 5.0 release were made against 5fb702911718a58f617bc774d846e6e4084da5d2, released in 4.4.0.

Most importantly, importlib_metadata 5 still retains the [tuple item access support](https://github.com/python/importlib_metadata/blob/009ace37032742922d5fa04c62f04cea703ade2d/importlib_metadata/__init__.py#L149-L151) (deprecated) added in v4.8.1.

**Comment by jacwalte** [comment]
@jaraco I updated my comment with the full content of the error provided by the ADO (Azure Dev Ops) task.

commands that ran the task.

```bash
source $CONDA/bin/activate
python -m pip install safety==2.1.1 bandit==1.7.4
safety check
bandit --recursive .
```

We were not specifying the version of importlib-metadata or that it be installed here.  I updated the python -m pip command to include importlib-metadata==4.13.0 and now everything is passing as expected.

new command
```bash
source $CONDA/bin/activate
python -m pip install importlib-metadata==4.13.0 safety==2.1.1 bandit==1.7.4
safety check
bandit --recursive .
```

Please let me know if I can provide more details.  

Thanks!
Jack Walters

**Comment by jaraco** [comment]
Thanks. Yes, I can confirm with that traceback that it's a different issue, the one reported in #409, and that this issue could still potentially affect stevedore too, if the deprecation isn't addressed.

**Comment by devturner** [comment]
I seem to be having this issue with 5.0.0 as well. 
`importlib-metadata==5.0.0` with `virtualvenvwrapper`:

`Traceback (most recent call last):
  File "/home/svc_github/.local/lib/python3.7/site-packages/stevedore/_cache.py", line 159, in _get_data_for_path
    with open(filename, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/svc_github/.cache/python-entrypoints/b7da1c40bfd4c6a4543cc4c51b88b58e80b6d1ef83e7609d76f0a85191c1b16f'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/svc_github/.local/lib/python3.7/site-packages/virtualenvwrapper/hook_loader.py", line 223, in <module>
    main()
  File "/home/svc_github/.local/lib/python3.7/site-packages/virtualenvwrapper/hook_loader.py", line 132, in main
    run_hooks(hook, options, args)
  File "/home/svc_github/.local/lib/python3.7/site-packages/virtualenvwrapper/hook_loader.py", line 161, in run_hooks
    hook_mgr = ExtensionManager(namespace)
  File "/home/svc_github/.local/lib/python3.7/site-packages/stevedore/extension.py", line 136, in __init__
    verify_requirements)
  File "/home/svc_github/.local/lib/python3.7/site-packages/stevedore/extension.py", line 218, in _load_plugins
    for ep in self.list_entry_points():
  File "/home/svc_github/.local/lib/python3.7/site-packages/stevedore/extension.py", line 207, in list_entry_points
    eps = list(_cache.get_group_all(self.namespace))
  File "/home/svc_github/.local/lib/python3.7/site-packages/stevedore/_cache.py", line 179, in get_group_all
    data = self._get_data_for_path(path)
  File "/home/svc_github/.local/lib/python3.7/site-packages/stevedore/_cache.py", line 162, in _get_data_for_path
    data = _build_cacheable_data(path)
  File "/home/svc_github/.local/lib/python3.7/site-packages/stevedore/_cache.py", line 110, in _build_cacheable_data
    for name, group_data in real_groups.items():
AttributeError: 'EntryPoints' object has no attribute 'items'
virtualenvwrapper.sh: There was a problem running the initialization hooks.

If Python could not import the module virtualenvwrapper.hook_loader,
check that virtualenvwrapper has been installed for
VIRTUALENVWRAPPER_PYTHON=/usr/bin/python3 and that PATH is
set properly.`

**Comment by jaraco** [comment]
@devturner Your issue is in #409.

**Comment by jaraco** [comment]
In 1343876, I've added a note to block the removal of the `DeprecatedTuple`, which deprecates the item access of an EntryPoint, until 2023-05-01 based on feedback in #409.
