### ISSUE TITLE
importlib_metadata does not find distributions in the current directory

### ISSUE THREAD

**Issue by benoit-pierre** [python/importlib_metadata#353]
I'm in a setuptools project directory, there's a `plover.egg-info` entry. This does not work:
```python
▸ python -c '__import__("importlib_metadata").files("plover")'
17:20:03> python -c '__import__("importlib_metadata").files("plover")'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.9/site-packages/importlib_metadata/__init__.py", line 1028, in files
    return distribution(distribution_name).files
  File "/usr/lib/python3.9/site-packages/importlib_metadata/__init__.py", line 967, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.9/site-packages/importlib_metadata/__init__.py", line 561, in from_name
    raise PackageNotFoundError(name)
importlib_metadata.PackageNotFoundError: No package metadata was found for plover
```
Even if the first entry in `sys.path` is `''`.

This work:
```python
▸ PYTHONPATH="$PWD" python -c '__import__("importlib_metadata").files("plover")'
▸ PYTHONPATH="." python -c '__import__("importlib_metadata").files("plover")'
```

**Comment by jaraco** [comment]
I see the same thing from the root of the project:

```
>>> list(importlib_metadata.Distribution.discover(path=['']))
[]
>>> list(importlib_metadata.Distribution.discover(path=['.']))
[<importlib_metadata.PathDistribution object at 0x1080b4070>]
```

**Comment by jaraco** [comment]
Diving deeper into the implementation:

```
>>> list(importlib_metadata.FastPath('').search(None))
[]
>>> list(importlib_metadata.FastPath('.').search(None))
[PosixPath('importlib_metadata.egg-info')]
```

**Comment by jaraco** [comment]
The issue is here:

https://github.com/python/importlib_metadata/blob/eda7021d0883ade7bd2bc55c6fd84207ba7ed174/importlib_metadata/__init__.py#L777

If `self.root` is the empty string, that call raises a FileNotFoundError and the results are suppressed.

**Comment by jaraco** [comment]
Looks like the bug was introduced in https://github.com/python/importlib_metadata/commit/11c147f89f43f2d29daa9f8b3f5aceb78ca43d0b when `self.root or '.'` was replaced with the erroneous `self.root or ''`.

**Comment by jaraco** [comment]
The latest code now works:

```
>>> import importlib_metadata
>>> list(importlib_metadata.Distribution.discover(path=['']))
[<importlib_metadata.PathDistribution object at 0x102c45d80>]
```

I've committed the bugfix to maint/2.x and released 2.1.2 and 4.8.2 with the fix.

**Comment by benoit-pierre** [comment]
Thanks.

There's something wrong with the changelog, see #355.

**Comment by jaraco** [comment]
Created https://bugs.python.org/issue45765 to track the fix in CPython.
