### ISSUE TITLE
Entry points fail to parse with indented definition on Python 2.7

### ISSUE THREAD

**Issue by jaraco** [python/importlib_metadata#36]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on Dec 11, 2018, 03:23

In [this job](https://gitlab.com/python-devs/importlib_metadata/-/jobs/132609452), I learned that the Python 2.7 ConfigParser fails to parse entry points as defined in Jinja2 due to excess indentation of the definition:

```
Traceback (most recent call last):
  File "importlib_metadata/tests/test_api.py", line 39, in test_entry_points
    scripts = importlib_metadata.entry_points()['console_scripts']
  File "importlib_metadata/api.py", line 202, in entry_points
    ordered = sorted(eps, key=by_group)
  File "importlib_metadata/api.py", line 200, in <genexpr>
    dist.entry_points for dist in distributions())
  File "importlib_metadata/api.py", line 146, in entry_points
    return EntryPoint._from_text(self.read_text('entry_points.txt'))
  File "importlib_metadata/api.py", line 70, in _from_text
    config.readfp(io.BytesIO(text))
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ConfigParser.py", line 324, in readfp
    self._read(fp, filename)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ConfigParser.py", line 512, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
MissingSectionHeaderError: File contains no section headers.
file: <???>, line: 2
'    [babel.extractors]\n'
```

**Comment by jaraco** [comment]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on Dec 11, 2018, 03:25

mentioned in commit feedaefa670496109f2f17b8e1bd42c593995ae3

**Comment by jaraco** [comment]
In GitLab by [@warsaw](https://gitlab.com/warsaw) on Dec 22, 2018, 19:15

closed via merge request !33

**Comment by jaraco** [comment]
In GitLab by [@warsaw](https://gitlab.com/warsaw) on Dec 22, 2018, 19:15

mentioned in commit b172bc45b41ca9e193285003cf2eb648676f2a0f
