### ISSUE TITLE
The result of requires() depends upon the installation mode

### ISSUE THREAD

**Issue by wimglenn** [python/importlib_metadata#394]
If a package was installed `.dist-info` style, we get requires like this:

```
>>> print('\n'.join(importlib_metadata.requires('wheel')))
pytest (>=3.0.0) ; extra == 'test'
pytest-cov ; extra == 'test'
```

However if the package was installed legacy style (e.g. `pip uninstall -y wheel; pip install wheel --no-binary wheel`) and there is a `PKG-INFO` + `.egg-info/requires.txt` file, we get requires like this:

```
>>> print('\n'.join(importlib_metadata.requires('wheel')))
pytest>=3.0.0; extra == "test"
pytest-cov; extra == "test"
```

These packages both actually have the same metadata, just represented in different ways.  Could the result be canonicalized, so that tools don't have to post-process them to get into a consistent format?

**Comment by jaraco** [comment]
My preference would be to neither normalize the format at the client or in importlib_metadata, but instead invest the energy in getting rid of the duplicate forms at the source. That is, let's find everywhere that '.egg-info' is generated and replace it with '.dist-info' so that importlib_metadata can ignore egg-info altogether.

I had thought that the use of egg-info was only a remnant of editable installs.

I tried to replicate the issue, but when I try to run `pip install wheel --no-binary wheel`, it fails, because pip requires wheel to install things from source, so it can't install wheel from source:

```
 importlib_metadata main $ py -3.10 -m pip install --no-binary wheel wheel
Collecting wheel
  Using cached wheel-0.37.1.tar.gz (66 kB)
  Installing build dependencies ... error
  error: subprocess-exited-with-error
  
  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 2
  ╰─> [51 lines of output]
      Collecting setuptools>=40.8.0
        Using cached setuptools-63.2.0-py3-none-any.whl (1.2 MB)
      Collecting wheel
        Using cached wheel-0.37.1.tar.gz (66 kB)
      ERROR: Exception:
      Traceback (most recent call last):
        File "/opt/homebrew/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 167, in exc_logging_wrapper
          status = run_func(*args)
        File "/opt/homebrew/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 247, in wrapper
          return func(self, options, args)
        File "/opt/homebrew/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 369, in run
          requirement_set = resolver.resolve(
        File "/opt/homebrew/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 92, in resolve
          result = self._result = resolver.resolve(
        File "/opt/homebrew/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 481, in resolve
          state = resolution.resolve(requirements, max_rounds=max_rounds)
        File "/opt/homebrew/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 348, in resolve
          self._add_to_criteria(self.state.criteria, r, parent=None)
        File "/opt/homebrew/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 172, in _add_to_criteria
          if not criterion.candidates:
        File "/opt/homebrew/lib/python3.10/site-packages/pip/_vendor/resolvelib/structs.py", line 151, in __bool__
          return bool(self._sequence)
        File "/opt/homebrew/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 155, in __bool__
          return any(self)
        File "/opt/homebrew/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 143, in <genexpr>
          return (c for c in iterator if id(c) not in self._incompatible_ids)
        File "/opt/homebrew/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 47, in _iter_built
          candidate = func()
        File "/opt/homebrew/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 206, in _make_candidate_from_link
          self._link_candidate_cache[link] = LinkCandidate(
        File "/opt/homebrew/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 297, in __init__
          super().__init__(
        File "/opt/homebrew/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 162, in __init__
          self.dist = self._prepare()
        File "/opt/homebrew/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 231, in _prepare
          dist = self._prepare_distribution()
        File "/opt/homebrew/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 308, in _prepare_distribution
          return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
        File "/opt/homebrew/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 438, in prepare_linked_requirement
          return self._prepare_linked_requirement(req, parallel_builds)
        File "/opt/homebrew/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 524, in _prepare_linked_requirement
          dist = _get_prepared_distribution(
        File "/opt/homebrew/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 67, in _get_prepared_distribution
          with build_tracker.track(req):
        File "/opt/homebrew/Cellar/python@3.10/3.10.5/Frameworks/Python.framework/Versions/3.10/lib/python3.10/contextlib.py", line 135, in __enter__
          return next(self.gen)
        File "/opt/homebrew/lib/python3.10/site-packages/pip/_internal/operations/build/build_tracker.py", line 122, in track
          self.add(req)
        File "/opt/homebrew/lib/python3.10/site-packages/pip/_internal/operations/build/build_tracker.py", line 92, in add
          raise LookupError(message)
      LookupError: https://files.pythonhosted.org/packages/c0/6c/9f840c2e55b67b90745af06a540964b73589256cb10cc10057c87ac78fc2/wheel-0.37.1.tar.gz (from https://pypi.org/simple/wheel/) (requires-python:!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*,>=2.7) is already being built: wheel from https://files.pythonhosted.org/packages/c0/6c/9f840c2e55b67b90745af06a540964b73589256cb10cc10057c87ac78fc2/wheel-0.37.1.tar.gz
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 2
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

Is there a different step I can use to replicate what you're finding?

Why not always install packages non-legacy style?

**Comment by wimglenn** [comment]
> Why not always install packages non-legacy style?

Sometimes we are not able to control the installation mode of the package, but still want to consume the metadata.

> Is there a different step I can use to replicate what you're finding?

I am not sure why you are not getting [this log message](https://github.com/pypa/pip/blob/22.2.1/src/pip/_internal/wheel_builder.py#L81-L84) in your setup. Weird!

Try using the [python image](https://hub.docker.com/_/python) and make sure that latest pip/setuptools are installed. 

```
❯ podman run --rm -it python:3.10.5-alpine3.15 sh
/ # pip --version
pip 22.0.4 from /usr/local/lib/python3.10/site-packages/pip (python 3.10)
/ # pip freeze --all
pip==22.0.4
setuptools==58.1.0
wheel==0.37.1
/ # pip uninstall -y wheel
Found existing installation: wheel 0.37.1
Uninstalling wheel-0.37.1:
  Successfully uninstalled wheel-0.37.1
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
/ # pip install -U pip setuptools
Requirement already satisfied: pip in /usr/local/lib/python3.10/site-packages (22.0.4)
Collecting pip
  Downloading pip-22.2.1-py3-none-any.whl (2.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 78.4 MB/s eta 0:00:00
Requirement already satisfied: setuptools in /usr/local/lib/python3.10/site-packages (58.1.0)
Collecting setuptools
  Downloading setuptools-63.2.0-py3-none-any.whl (1.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 83.0 MB/s eta 0:00:00
Installing collected packages: setuptools, pip
  Attempting uninstall: setuptools
    Found existing installation: setuptools 58.1.0
    Uninstalling setuptools-58.1.0:
      Successfully uninstalled setuptools-58.1.0
  Attempting uninstall: pip
    Found existing installation: pip 22.0.4
    Uninstalling pip-22.0.4:
      Successfully uninstalled pip-22.0.4
Successfully installed pip-22.2.1 setuptools-63.2.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
/ # pip install --no-binary wheel wheel
Collecting wheel
  Downloading wheel-0.37.1.tar.gz (66 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 66.4/66.4 kB 18.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Skipping wheel build for wheel, due to binaries being disabled for it.
Installing collected packages: wheel
  Running setup.py install for wheel ... done
Successfully installed wheel-0.37.1
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
/ # python3 -c 'import wheel; print(wheel.__file__)'
/usr/local/lib/python3.10/site-packages/wheel/__init__.py
/ # cat /usr/local/lib/python3.10/site-packages/wheel-0.37.1-py3.10.egg-info/requires.txt 

[test]
pytest>=3.0.0
pytest-cov
```

**Comment by jaraco** [comment]
Aha - so I must have been using an environment with PIP_USE_PEP517=1. When I run with `env PIP_USE_PEP517=0 py -3.10 -m pip install --no-binary wheel wheel`, it now uses the legacy `setup.py install`. What's strange is I'd looked for that environment variable and found it not to be set. Even now, I'm unsure why in my environment pip is behaving as if that environment is set, even though it's not:

```
$ env | grep PIP
PIP_NO_PYTHON_VERSION_WARNING=1
```

**Comment by jaraco** [comment]
My recommendation for now, while both formats exist, is that if you need a normalized form, use `packaging` to normalize the requirements. Consider this dockerfile:

```Dockerfile
FROM jaraco/multipy-tox
RUN py -m pip install packaging
RUN py -c "import importlib_metadata as md, packaging.requirements; list(map(print, map(packaging.requirements.Requirement, md.requires('wheel'))))" > before.txt
RUN py -c "import importlib_metadata as md; print(md.distribution('wheel')._path)" > before-loc.txt
RUN pip-run -q setuptools -- -m pip install --no-binary wheel wheel --force-reinstall
RUN py -c "import importlib_metadata as md, packaging.requirements; list(map(print, map(packaging.requirements.Requirement, md.requires('wheel'))))" > after.txt
CMD cat before-loc.txt; cat before.txt; diff before.txt after.txt
```

When I run that file, I get this output:

```
/usr/local/lib/python3.11/dist-packages/wheel-0.37.1.dist-info
pytest>=3.0.0; extra == "test"
pytest-cov; extra == "test"
```

That shows that (a) the syntax as found in `dist-info` is in fact non-standard, (b) the syntax in egg-info matches the standard format output by `packgaing`, and (c), by using packaging to normalize the strings, they match exactly.

The goal of importlib_metadata (and importlib.metadata) is to reflect the metadata as found in the package, and leave it to the consumer to apply more sophisticated processing of those.

Would that approach work for your use case?

**Comment by wimglenn** [comment]
That is acceptable for my use-case, but I do wonder if canonicalizing the requires format may still be a good idea for `importlib.metadata`. I can see users assuming this will be a certain output format and parsing them without using using `packaging`, only to get stung when an unexpected format gets returned.

Anyway feel free to close the issue if you feel it's out of scope for `importlib_metadata`.

**Comment by jaraco** [comment]
> using some simple Python code for parsing them, without using using `packaging`

This is the crux of the issue. I'd like for importlib metadata not to have to duplicate and maintain consistency with packaging. Basically, the rule is that if `packaging` implements it, then importlib metadata should not. If at some point `packaging` becomes part of the standard library, then I would definitely consider for importlib metadata to return objects from that library instead of the raw internal form. In the meantime, the design is for users to get the raw representation (and use packaging themselves where appropriate).
