### ISSUE TITLE
Local distribution not found for package using the 'src' layout

### ISSUE THREAD

**Issue by jaraco** [python/importlib_metadata#42]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on Jan 29, 2019, 01:42

In the [Distribution.find_local method](https://gitlab.com/python-devs/importlib_metadata/blob/6455168580479cecbcdb6bd27c52462edf7c0169/importlib_metadata/api.py#L181-187), I assumed, apparently incorrectly, that performing a `setup.py develop` or `pip install -e .` on a package would generate the metadata in `.` as it does on projects I've maintained.

I recently inherited the configparser project, which uses the 'src' layout, and I discover that in that project, setuptools generates the egg-info metadata in 'src', and in this condition, `find_local` gets a ValueError because there's no metadata found in `.`:

```
configparser master $ python setup.py egg_info                                                                                                                                           
running egg_info
creating src/configparser.egg-info
writing src/configparser.egg-info/PKG-INFO
writing dependency_links to src/configparser.egg-info/dependency_links.txt
writing requirements to src/configparser.egg-info/requires.txt
writing top-level names to src/configparser.egg-info/top_level.txt
writing manifest file 'src/configparser.egg-info/SOURCES.txt'
reading manifest file 'src/configparser.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'src/configparser.egg-info/SOURCES.txt'
configparser master $ pip-run -q importlib_metadata==0.8                                                                                                                                 
Python 3.7.2 (v3.7.2:9a3ffc0492, Dec 24 2018, 02:44:43) 
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import importlib_metadata
>>> importlib_metadata.api.local_distribution()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/importlib_metadata/api.py", line 326, in local_distribution
    return Distribution.find_local()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/importlib_metadata/api.py", line 186, in find_local
    dist, = dists
ValueError: not enough values to unpack (expected 1, got 0)
>>> 
```

I'm not sure what to do... because in the general case, any package can decide to have its metadata built wherever it likes (there's nothing special about 'src').

I think the recommendation from PEP 517 and PEP 518 is that tools that need metadata for a package that's on the file system, the way to do that is to call the hooks. I think importlib_metadata should probably do this rather than expecting the metadata to be in `.`.

I'm also _tempted_ to find metadata in `.` or `src` as a short-term, hacky workaround. But before I do that, I'll try to see if I can make the pep517 package help out in this regard.

**Comment by jaraco** [comment]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on Feb 14, 2019, 15:24

changed the description

**Comment by jaraco** [comment]
In GitLab by [@warsaw](https://gitlab.com/warsaw) on May 16, 2019, 22:44

> I think the recommendation from PEP 517 and PEP 518 is that tools that need metadata for a package that's on the file system, the way to do that is to call the hooks. I think importlib_metadata should probably do this rather than expecting the metadata to be in `.`. 

I should probably read those PEPs, but can you summarize what it means to "call the hooks"?

> I'm also *tempted* to find metadata in `.` or `src` as a short-term, hacky workaround. But before I do that, I'll try to see if I can make the pep517 package help out in this regard.

Yeah, packages do all sorts of crazy things, but I bet handling `.` and `src` would cover at least 80/20 if not 90/10.  Would it be terrible to try to parse out the `packages` or `package_dir` keys to `setup()` in `setup.py`?  E.g. in Mailman 3 core we have:

```
setup(
    #...
    packages        = find_packages('src'),
    package_dir     = {'': 'src'},
    #...
    )
```

But maybe that's crufty old stuff we can't depend on?

**Comment by jaraco** [comment]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on May 18, 2019, 18:38

> I should probably read those PEPs, but can you summarize what it means to "call the hooks"?

It mainly means to call the `prepare_metadata_for_build_wheel` hook on `.`, which will produce the `dist-info` directory that could be passed to a `PathDistribution` to parse the metadata. I don't believe this hook is currently exposed by the [pep517 library](https://pypi.org/project/pep517), so it might require adding something like the `pep517.build` command to have [something like](https://github.com/pypa/pep517/issues/26) `pep517.build-meta`.

> Would it be terrible to try to parse setup.py?

Yes, or pretty close. It wouldn't help for projects that are using declarative config (setup.cfg). I'm not sure if setuptools currently supports `package_dir` declarations in declarative config, but if it doesn't currently, it probably will soon.

Moreover, for projects not using setuptools (those using flit, etc.), parsing setup.py will have no benefit. If we can get this right for PEP 517, it will support legacy and emergent approaches.

**Comment by jaraco** [comment]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on May 19, 2019, 24:20

mentioned in commit 8a62944e07394889998bb7513167c693783b6c29

**Comment by jaraco** [comment]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on May 19, 2019, 24:27

In [this branch](https://github.com/pypa/pep517/tree/feature/build-meta-command/pep517), I've started work on a `build-meta` command/API for the `pep517` package and in the [pep517-metadata branch](https://gitlab.com/python-devs/importlib_metadata/tree/feature/pep517-metadata), I demonstrate how that might be used to load that metadata using that library.

I have some concerns with this approach:

- [x] Currently the process assumes the "local" package is in `.`. That's fine for a default, but it really should be something that can be supplied.
- [x] The heuristic fallback assumes that the metadata has been built. Perhaps a better approach would be not to have a fallback, but to require a PEP 517 project or configure it as one for the duration of the metadata build.
- [ ] It depends on pep517 which depends on toml, two dependencies not available in stdlib.
- [ ] It's slow to build and likely requires network access to build metadata.
- [ ] It requires writing to the file system.

I don't think there's anything we can do about the last two aspects - that's just what our ecosystem demands.

**Comment by jaraco** [comment]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on May 20, 2019, 21:59

In the latest work on pep517, I've added support for building the metadata from any location (doesn't have to be `.`). In the pep517-metadata branch, the code now uses that pre-release version to unconditionally load the metadata using pep517, meaning the heuristic and assumption about pre-built metadata are no longer a concern.

Although the [tests are failing in CI](https://gitlab.com/python-devs/importlib_metadata/-/jobs/215199451) (on some builds only), that's due to bugs in flit, bugs that won't exist if that code is properly released.

I've observed a new concern:

- [ ] pep517 metadata builds emit a lot of noise to stdout.

There may be something we can do about that, though I'm not sure it's worth the trouble this early in the exploration.

What I'm mainly interested in right now is feedback from @warsaw on the concept. Should I proceed with making a pull request in pep517 upstream? What do you think about the stdlib support? Would these 'local distribution' metadata simply not be available when pep517 isn't installed (that's what I'm thinking)?

**Comment by jaraco** [comment]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on May 22, 2019, 13:04

At this point, based on my findings in !67, I believe either the `pep517` project should own the "local distribution metadata" functionality or it should be owned by another third-party library (preferably the former). The dependency tree sort-of demands it. My inclination now is for this project to remove the `local_distribution` and `Distribution.find_local` functionality.

**Comment by jaraco** [comment]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on May 22, 2019, 13:14

mentioned in commit 4098acb0d7fcf44fa66f34608f86ad965c3b18c3

**Comment by jaraco** [comment]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on May 22, 2019, 13:17

mentioned in merge request !69

**Comment by jaraco** [comment]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on May 24, 2019, 19:32

closed via commit 4098acb0d7fcf44fa66f34608f86ad965c3b18c3

**Comment by jaraco** [comment]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on May 24, 2019, 19:32

mentioned in commit 89be403fefa5a10d59694614f56d92838facd12a

**Comment by jaraco** [comment]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on May 24, 2019, 19:32

closed via merge request !69
