### ISSUE TITLE
Cannot get metadata from .egg-info files

### ISSUE THREAD

**Issue by jaraco** [python/importlib_metadata#43]
In GitLab by [@chrisjbillington](https://gitlab.com/chrisjbillington) on Feb 10, 2019, 23:18

I'm using importlib_metadata 0.8 on Python 3.7 on Arch Linux.

The following example shows that pyserials metadata can't be found by importlib_metadata, even though pkg_resources has it in the working_set:

```python
import pkg_resources
import importlib_metadata

for dist in pkg_resources.working_set:
    if dist.project_name == 'pyserial':
        print(dist.path)
        print(dist.version)

importlib_metadata.version('pyserial')
```

this gives:

```
/usr/lib/python3.7/site-packages/pyserial-3.4-py3.7.egg-info
3.4
Traceback (most recent call last):
  File "196.py", line 9, in <module>
    importlib_metadata.version('pyserial')
  File "/usr/lib/python3.7/site-packages/importlib_metadata/api.py", line 345, in version
    return distribution(package).version
  File "/usr/lib/python3.7/site-packages/importlib_metadata/api.py", line 310, in distribution
    return Distribution.from_name(package)
  File "/usr/lib/python3.7/site-packages/importlib_metadata/api.py", line 158, in from_name
    raise PackageNotFoundError(name)
importlib_metadata.api.PackageNotFoundError: pyserial
```

The thing about pyserial is that its import name ('serial') does not match its project name ('pyserial'), which might have something to do with it. importlib_metadata.version gives the same exception if I input 'serial', however.

**Comment by jaraco** [comment]
In GitLab by [@chrisjbillington](https://gitlab.com/chrisjbillington) on Feb 10, 2019, 23:18

changed the description

**Comment by jaraco** [comment]
In GitLab by [@chrisjbillington](https://gitlab.com/chrisjbillington) on Feb 11, 2019, 02:48

So it turns out it has nothing to do with pyserial's name.

It's the fact that my .egg-info for pyserial is a file, and not a directory. Over on Anaconda Python on Windows, it's a folder. The single file on linux corresponds to the PKG-INFO file within the folder.

Reading up on this, it seems that .egg-info is allowed to be a file and so it can't be assumed it's a directory. So this looks like maybe an invalid assumption being made by importlib_metadata, if I'm understanding correctly.

**Comment by jaraco** [comment]
In GitLab by [@chrisjbillington](https://gitlab.com/chrisjbillington) on Feb 11, 2019, 03:37

changed title from **Can{-'t get metadata for pyserial-}** to **Can{+not get metadata from .egg-info files+}**

**Comment by jaraco** [comment]
In GitLab by [@chrisjbillington](https://gitlab.com/chrisjbillington) on Feb 11, 2019, 04:23

mentioned in merge request !38

**Comment by jaraco** [comment]
In GitLab by [@tliu61](https://gitlab.com/tliu61) on Feb 24, 2019, 04:27

Yes, according to [The Internal Structure of Python Eggs](https://svn.python.org/projects/sandbox/trunk/setuptools/doc/formats.txt), the Project Metadata section third paragraph: 
> Because it's possible for this (PKG-INFO) to be the only metadata file included, ``.egg-info`` format eggs are not required to be a directory; they can just be a ``.egg-info`` file that directly contains the ``PKG-INFO`` metadata.

**Comment by jaraco** [comment]
In GitLab by [@warsaw](https://gitlab.com/warsaw) on May 6, 2019, 14:58

`.egg-info` files are produced by distutils, directories by setuptools.

**Comment by jaraco** [comment]
In GitLab by [@Lawouach](https://gitlab.com/Lawouach) on May 7, 2019, 13:22

Hi all, I wonder if I see the same issue here https://github.com/pytest-dev/pluggy/issues/205

What would be the best way to reproduce in a simple fashion though?

**Comment by jaraco** [comment]
In GitLab by [@warsaw](https://gitlab.com/warsaw) on May 7, 2019, 15:50

mentioned in merge request !57

**Comment by jaraco** [comment]
In GitLab by [@warsaw](https://gitlab.com/warsaw) on May 7, 2019, 20:20

closed via merge request !57

**Comment by jaraco** [comment]
In GitLab by [@warsaw](https://gitlab.com/warsaw) on May 7, 2019, 20:20

mentioned in commit 2ca45910d11c792d85bec1e418af9109ce473dab
