### ISSUE TITLE
Should we augment the `find_distributions()` lookup machinery?

### ISSUE THREAD

**Issue by jaraco** [python/importlib_metadata#57]
In GitLab by [@warsaw](https://gitlab.com/warsaw) on May 8, 2019, 15:35

Currently we add three "finders" to `sys.meta_path` and each of these has a `find_distributions()` method.  We document this as the way to hook into the system by third parties.  These get added when `importlib_metadata` is imported.

In our port to CPython, we're doing the same thing, which is a little weird because:
* these finders aren't available until `importlib.metadata` is imported
* this increases the size of `sys.meta_path` and that could potentially have a global performance impact

What might make more sense in the stdlib version is to add the `find_distributions()` methods to items on `sys.path_hooks` and then modify the `PathFinder` entry on `sys.meta_path` to traverse down into `sys.path_hooks` entries.  This would make sense if there are already natural places to tuck `find_distributions()` into.

Whatever we decide to do, we need to make sure that the stdlib version and standalone version are aligned, so third party users have consistency for all supported versions of Python.

**Reminder**  We also need to add documentation to the CPython import machinery (library and language reference) documenting the `find_distributions()` API.

**Comment by jaraco** [comment]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on May 9, 2019, 24:29

The work in !60 drastically simplifies the need here. Now I think all that needs to happen is for the standard `PathFinder` to inherit the methods from `MetadataPathFinder`.

**Comment by jaraco** [comment]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on May 10, 2019, 24:52

mentioned in commit c5bf21315214bf0827fd6555954e543fc931929b

**Comment by jaraco** [comment]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on May 10, 2019, 01:05

In the aforementioned commit, I've separated the `NullFinder` from the `PathDistributionFinder`, with the latter being the functionality that needs to be installed in the `importlib.machinery.PathFinder`.

However, after having a look at cpython, I'm not sure how readily this functionality can be incorporated into `_bootstrap_external.py`. The class requires imports from much of importlib.metadata:

```
contextlib
zipfile
pathlib
re
itertools
importlib.metadata.api
importlib.metadata.abc
sys
```

@brettcannon Will it be possible to derive `PathFinder` from [this PathDistributionFinder](https://gitlab.com/python-devs/importlib_metadata/blob/c5bf21315214bf0827fd6555954e543fc931929b/importlib_metadata/_hooks.py#L52-99) or otherwise incorporate that functionality into `PathFinder`, given all of the imports on which it relies? I imagine `importlib.metadata.abc` is the only one that would need to be imported at import time, and it should be possible not to derive from the DistributionFinder abc.

**Comment by jaraco** [comment]
In GitLab by [@brettcannon](https://gitlab.com/brettcannon) on May 10, 2019, 18:07

So you're asking if that list of modules can be imported so as to make `importlib.machinery.PathFinder` inherit from `PathDistributionFinder`? If that is the question then the answer is "no" as most of those modules are not implemented in C and that's a requirement for `importlib._bootstrap_external`.

If you're asking something else then I'm not sure what it is. :)

**Comment by jaraco** [comment]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on May 10, 2019, 18:37

@brettcannon My description was vague because I'm trying not to be prescriptive about the solution. Ulitmately, I'd like for `PathFinder` to have a `find_distributions` method (with the implementation as found on `MetadataPathFinder`).

Ideally (though secondarily), it would also be a subclass of `DistributionFinder`. It sounds like being a `DistributionFinder` would require `DistributionFinder` to be implemented in C, so that's probably not viable, so let's set that aside for now.

Would it be possible for a method in `importlib._bootstrap_external` to internally proxy to that functionality, something like:

```
class PathFinder:
    def find_distributions(self, *args, **kwargs):
        from importlib.metadata import _hooks
        return _hooks.MetadataPathFinder.find_distributions(self, *args, **kwargs)
```

**Comment by jaraco** [comment]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on May 10, 2019, 18:45

I see now how that doesn't really work - as `find_distributions` really needs `self` to be a `MetadataPathFinder`. Is it possible to inline all of those methods into PathFinder if they all import their references late?

**Comment by jaraco** [comment]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on May 10, 2019, 18:58

In [this commit](https://github.com/jaraco/cpython/commit/e6b500b0bd5dab9c9125ff5e7d928e186f297062), I attempted to inline the functionality... but after running `make regen-importlib && make` and then running tests, I see this failure (and many others like it):

```
======================================================================
ERROR: test_zip_version (test.test_importlib.test_zip.TestZip)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jaraco/code/public/cpython/Lib/test/test_importlib/test_zip.py", line 26, in test_zip_version
    self.assertEqual(version('example'), '21.12')
  File "/Users/jaraco/code/public/cpython/Lib/importlib/metadata/api.py", line 328, in version
    return distribution(package).version
  File "/Users/jaraco/code/public/cpython/Lib/importlib/metadata/api.py", line 293, in distribution
    return Distribution.from_name(package)
  File "/Users/jaraco/code/public/cpython/Lib/importlib/metadata/api.py", line 137, in from_name
    dists = resolver(name)
  File "<frozen importlib._bootstrap_external>", line 1375, in find_distributions
AttributeError: 'str' object has no attribute '_search_paths'

----------------------------------------------------------------------
```

**Comment by jaraco** [comment]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on May 10, 2019, 19:02

Aha. I figured it out - PathFinder isn't instantiated... so `find_distributions` needs to be a classmethod.

**Comment by jaraco** [comment]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on May 10, 2019, 19:50

Here's [what I'm currently proposing](https://github.com/jaraco/cpython/pull/1). Tests are passing with this code merged.

**Comment by jaraco** [comment]
In GitLab by [@brettcannon](https://gitlab.com/brettcannon) on May 11, 2019, 01:12

It doesn't have to be in C, it just needs to avoid needing anything that isn't a built-in module. You can potentially do a local import if necessary, but those types of imports have their own issues so avoiding them as much as possible is still a good thing.

**Comment by jaraco** [comment]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on May 11, 2019, 02:05

It looks like this technique will work. I've updated the `cpython` branch of this project to reflect that the functionality is now in `_bootstrap_external`. This approach complicates the migration process, as now the files can't be simply copied, but have to be manually merged. I'll update the wiki accordingly.

**Comment by jaraco** [comment]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on May 14, 2019, 13:25

removed milestone

**Comment by jaraco** [comment]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on May 14, 2019, 13:37

mentioned in commit 80d04fd334ab6f96df836f47bcf37b91f059ec4a

**Comment by jaraco** [comment]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on May 18, 2019, 17:53

In the latest pull request, `find_distributions` is implemented natively on `PathFinder`.

**Comment by jaraco** [comment]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on May 18, 2019, 17:53

closed
