### ISSUE TITLE
pathlib2 is called but not required in setup.py

### ISSUE THREAD

**Issue by jaraco** [python/importlib_metadata#65]
In GitLab by [@devthat](https://gitlab.com/devthat) on May 29, 2019, 08:49

Hello,

I am tracking down a bug that is triggerd by tox using pluggy using importlib_metadata.

Please have a look at the following stacktrace.
```shell
Traceback (most recent call last):
  File "/home/vagrant/tox_venv/bin/tox", line 7, in <module>
    from tox import cmdline
  File "/home/vagrant/tox_venv/lib/python3.4/site-packages/tox/__init__.py", line 9, in <module>
    import pluggy
  File "/home/vagrant/tox_venv/lib/python3.4/site-packages/pluggy/__init__.py", line 16, in <module>
    from .manager import PluginManager, PluginValidationError
  File "/home/vagrant/tox_venv/lib/python3.4/site-packages/pluggy/manager.py", line 6, in <module>
    import importlib_metadata
  File "/home/vagrant/tox_venv/lib/python3.4/site-packages/importlib_metadata/__init__.py", line 14, in <module>
    from ._compat import (
  File "/home/vagrant/tox_venv/lib/python3.4/site-packages/importlib_metadata/_compat.py", line 26, in <module>
    import pathlib2 as pathlib
ImportError: No module named 'pathlib2'
```

This fails because pathlib2 is not installed. The critical code is from importlib_metadata. But since pathlib2 is not required in setup.py it is never installed.

Bests
Jonathan

**Comment by jaraco** [comment]
In GitLab by [@warsaw](https://gitlab.com/warsaw) on May 29, 2019, 21:52

What version of Python do you see this error in?  We only include `pathlib2` conditionally.  From `setup.py`:

```
[options]
python_requires = >=2.7,!=3.0,!=3.1,!=3.2,!=3.3
install_requires =
    zipp>=0.5
    pathlib2; python_version=='3.4.*' or python_version < '3'
    contextlib2; python_version < '3'
    configparser; python_version < '3'
packages = find:
```

**Comment by jaraco** [comment]
In GitLab by [@devthat](https://gitlab.com/devthat) on May 30, 2019, 18:15

Hallo Barry,

thank you for your reply.

The job is failing on one of our old buildservers. It is running Ubuntu 14.04. We are installing tox in a 3.4 virtualenv and run test for python 2.7 and 3.4.

I did not succeed in easily recreating the error on my home machine and unfortunately I will only be back to work next monday. So I cannot give you more details until then.

Best regards  
Jonathan

**Comment by jaraco** [comment]
In GitLab by [@devthat](https://gitlab.com/devthat) on Jun 3, 2019, 11:46

Please run the following to reproduce the error. Nothing else is required.
```shell
docker run --rm python:3.4.3 sh -c "pip install tox && tox"
```

**Comment by jaraco** [comment]
In GitLab by [@devthat](https://gitlab.com/devthat) on Jun 3, 2019, 14:08

I just realized that running the following resolves the problem. 
```shell
docker run --rm python:3.4.3 sh -c "pip install pip --upgrade && pip install tox && tox"
```
Which means this is not an issue of importlib_metadata but an out of date pip version that is not able to parse the requirements. I am closing this issue. Thank you for your time!

**Comment by jaraco** [comment]
In GitLab by [@devthat](https://gitlab.com/devthat) on Jun 3, 2019, 14:08

closed
