### ISSUE TITLE
Test failures with Python 3.7

### ISSUE THREAD

**Issue by jaraco** [python/importlib_metadata#72]
In GitLab by [@FRidh](https://gitlab.com/FRidh) on Jun 15, 2019, 17:36

```
FAIL: test_for_name_does_not_exist (importlib_metadata.tests.test_api.APITests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/importlib_metadata-0.18/importlib_metadata/tests/test_api.py", line 43, in test_for_name_does_not_exist
    distribution('does-not-exist')
AssertionError: PackageNotFoundError not raised

======================================================================
FAIL: test_for_name_does_not_exist (importlib_metadata.tests.test_main.BasicTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/importlib_metadata-0.18/importlib_metadata/tests/test_main.py", line 33, in test_for_name_does_not_exist
    Distribution.from_name('does-not-exist')
AssertionError: PackageNotFoundError not raised

----------------------------------------------------------------------
```

I can get you the versions of dependenceis when needed.

**Comment by jaraco** [comment]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on Aug 31, 2019, 15:00

These test failures aren't happening in continuous integration. Perhaps that's because they were fixed in the latest releases. Please comment or re-open if you're still seeing these errors.

**Comment by jaraco** [comment]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on Aug 31, 2019, 15:00

closed
