### ISSUE TITLE
AttributeError: 'PosixPath' object has no attribute 'read_text'

### ISSUE THREAD

**Issue by jaraco** [python/importlib_metadata#79]
In GitLab by [@mratsim](https://gitlab.com/mratsim) on Jul 22, 2019, 14:26

I get the following stacktrace when trying to use pytest which imports importlib_metadata:

```
$  pytest eth2spec/test/phase_0/block_processing/test_process_deposit.py 
Traceback (most recent call last):
  File "/usr/bin/pytest", line 11, in <module>
    load_entry_point('pytest==4.6.4', 'console_scripts', 'pytest')()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2843, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2434, in load
    return self.resolve()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2440, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.7/site-packages/pytest.py", line 8, in <module>
    from _pytest.assertion import register_assert_rewrite
  File "/usr/lib/python3.7/site-packages/_pytest/assertion/__init__.py", line 13, in <module>
    from _pytest.assertion import rewrite
  File "/usr/lib/python3.7/site-packages/_pytest/assertion/rewrite.py", line 24, in <module>
    from _pytest.assertion import util
  File "/usr/lib/python3.7/site-packages/_pytest/assertion/util.py", line 11, in <module>
    import _pytest._code
  File "/usr/lib/python3.7/site-packages/_pytest/_code/__init__.py", line 7, in <module>
    from .code import Code  # noqa
  File "/usr/lib/python3.7/site-packages/_pytest/_code/code.py", line 15, in <module>
    import pluggy
  File "/usr/lib/python3.7/site-packages/pluggy/__init__.py", line 16, in <module>
    from .manager import PluginManager, PluginValidationError
  File "/usr/lib/python3.7/site-packages/pluggy/manager.py", line 6, in <module>
    import importlib_metadata
  File "/usr/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 471, in <module>
    __version__ = version(__name__)
  File "/usr/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 438, in version
    return distribution(package).version
  File "/usr/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 226, in version
    return self.metadata['Version']
  File "/usr/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 214, in metadata
    self.read_text('METADATA')
  File "/usr/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 398, in read_text
    return self._path.joinpath(filename).read_text(encoding='utf-8')
AttributeError: 'PosixPath' object has no attribute 'read_text'
```

Package version:
- pytest-4.6.4
- importlib-metadata-0.18
- python 3.7.3

**Comment by jaraco** [comment]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on Jul 28, 2019, 01:10

Wow. That's awful.

...and weird because [the Python docs indicate that PosixPath does have such a method](https://docs.python.org/3/library/pathlib.html#pathlib.Path.read_text). There's got to be something else going on there. You'll notice in your call stack that all you have to do is call `import importlib_metadata` and the error occurs. Can you try that by itself and do you still get the error?

Are you able to inspect that code and see what `self._path.joinpath(filename)` is at that point why it doesn't have a `read_text`?

**Comment by jaraco** [comment]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on Aug 31, 2019, 14:49

Searching that exact error message, I see other users who've encountered it on Python 3.4 (which didn't have pathlib) but also [this case](https://github.com/aio-libs/aiohttp/issues/3977) where the cause was "pathlib was installed". I suspect you have a similar issue in your environment. Feel free to comment if you have more information.

**Comment by jaraco** [comment]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on Aug 31, 2019, 14:49

closed

**Comment by matteomedioli** [comment]
Same issue running on Python 3.8.5
`pip3 install pathlib`

**Comment by jaraco** [comment]
Indeed. I'm able to replicate the issue:

```
~ $ python3.8 -m pip-run pathlib importlib_metadata -- -c "import importlib_metadata"
Collecting pathlib
  Using cached pathlib-1.0.1.tar.gz (49 kB)
  Preparing metadata (setup.py) ... done
Using legacy 'setup.py install' for pathlib, since package 'wheel' is not installed.
Installing collected packages: pathlib
    Running setup.py install for pathlib ... done
Successfully installed pathlib-1.0.1
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/importlib_metadata/__init__.py", line 602, in <module>
    __version__ = version(__name__)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/importlib_metadata/__init__.py", line 564, in version
    return distribution(distribution_name).version
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/importlib_metadata/__init__.py", line 264, in version
    return self.metadata['Version']
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/importlib_metadata/__init__.py", line 252, in metadata
    self.read_text('METADATA')
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/importlib_metadata/__init__.py", line 524, in read_text
    return self._path.joinpath(filename).read_text(encoding='utf-8')
AttributeError: 'PosixPath' object has no attribute 'read_text'
```

**Comment by jaraco** [comment]
Oh, so I see pathlib was last released in 2014 and is not maintained. It's code was hosted on Bitbucket, meaning it's no longer even available for inspection. I do see that `pip install pathlib` doesn't always supersede the stdlib version, but when it does, you'll get this error.

The fix is to stop using pathlib.
