### ISSUE TITLE
Resolver does not handle '-', '.', '_' characters in package name

### ISSUE THREAD

**Issue by jaraco** [python/importlib_metadata#81]
In GitLab by [@mshriver](https://gitlab.com/mshriver) on Aug 19, 2019, 19:33

Setuptools package naming includes agnosticism of the use of `-`,`_`, and `.` in package names.

PyPi will also cleanly handle replacement of these characters in package names, resolving `package_name` to `package.name` if that is what is specified for the distribution.

Resolving metadata for a given imported package name which does not match the distribution name exactly fails with `PackageNotFoundError`.

I believe importlib_metadata should properly resolve names regardless of the use of `-`,`_`, and `.` in order to work with the naming conventions defined by PyPA.

```
Python 3.7.3 (default, May 11 2019, 00:38:04) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.4.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import importlib_metadata                                                                                             

In [2]: importlib_metadata.metadata('widgetastic_patternfly')                                                                 
---------------------------------------------------------------------------
PackageNotFoundError                      Traceback (most recent call last)
<ipython-input-2-6076e0b12a08> in <module>
----> 1 importlib_metadata.metadata('widgetastic_patternfly')

~/[redacted]/lib64/python3.7/site-packages/importlib_metadata/__init__.py in metadata(package)
    433     :return: An email.Message containing the parsed metadata.
    434     """
--> 435     return Distribution.from_name(package).metadata
    436 
    437 

~/[redacted]/lib64/python3.7/site-packages/importlib_metadata/__init__.py in from_name(cls, name)
    182                 return dist
    183         else:
--> 184             raise PackageNotFoundError(name)
    185 
    186     @classmethod

PackageNotFoundError: widgetastic_patternfly

In [3]: importlib_metadata.metadata('widgetastic.patternfly')                                                                 
Out[3]: <email.message.Message at 0x7f064c0464a8>

```

**Comment by jaraco** [comment]
In GitLab by [@mshriver](https://gitlab.com/mshriver) on Aug 19, 2019, 19:35

changed title from **Resolver does not handle {-`-`, `.`, `_`-} characters in package name** to **Resolver does not handle {+'-', '.', '_'+} characters in package name**

**Comment by jaraco** [comment]
In GitLab by [@mshriver](https://gitlab.com/mshriver) on Aug 19, 2019, 19:35

changed the description

**Comment by jaraco** [comment]
In GitLab by [@mshriver](https://gitlab.com/mshriver) on Aug 19, 2019, 23:37

If I'm using it wrong, I'm looking forward to learning how!  Thanks.

**Comment by jaraco** [comment]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on Aug 31, 2019, 14:11

The current design is that the interface demands the canonical name for an installed package. There is _some_ normalization of package names done in some aspects of the packaging infrastructure, but it's not universal and I believe it's undesirable that `.`, `-`, and `_` are treated as the same character in all of packaging.

I tried doing some experiments using pip 19.2.3 and got some interesting results:

Installing `widgetastic.patternfly` showed `Successfully installed widgetastic.patternfly-1.0.0`. Installing `widgetastic_patternfly` or `widgetastic-patternfly` both showed `Successfully installed widgetastic-patternfly` (no version indicated). So there are already some inconsistencies or bugs revealed by using the non-canonical name.

Looking at the package on PyPI, I can see that the package name appears to use a `.` and `-` and `_` are normalized to that `.`:

```
~ $ http --headers https://pypi.org/project/widgetastic-patternfly/ | head -n 1                                                              
HTTP/1.1 301 Moved Permanently
~ $ http --headers https://pypi.org/project/widgetastic.patternfly/ | head -n 1                                                              
HTTP/1.1 200 OK
~ $ http --headers https://pypi.org/project/widgetastic_patternfly/ | head -n 1                                                              
HTTP/1.1 301 Moved Permanently
```

Both of these mechanisms are for package name normalization around discovery in the package index. It's not clear to me that this same normalization should also be applied here as well.

Probably the reason pip was unable to resolve the version of `widgetastic-patternfly` after installing it was because even pkg_resources doesn't recognize this apparent normalization:

```
~ $ pip-run -q --no-deps widgetastic-patternfly                                                                                              
Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 16:52:21) 
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import importlib_metadata
>>> importlib_metadata.version('widgetastic.patternfly')
'1.0.0'
>>> import pkg_resources
>>> pkg_resources.get_distribution('widgetastic.patternfly').version
'1.0.0'
>>> pkg_resources.get_distribution('widgetastic-patternfly').version
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 481, in get_distribution
    dist = get_provider(dist)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 357, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'widgetastic-patternfly' distribution was not found and is required by the application
```

My best recommendation for now is to use the canonical name (`widgetastic.patternfly` in this case) to locate the distribution/metadata and avoid relying on the normalization rules you discovered in warehouse.

```
>>> importlib_metadata.version('widgetastic.patternfly')
'1.0.0'
```

The canonical name is "widgetastic.patternfly". Just use that everywhere.

If you can find a sanctioned document describing the rules for normalization and how they should be applied in this aspect, then I'd be happy to apply them, but in the absence of clear specification and guidance, I'm reluctant to add ambiguity and violate the "preferably one" best way to do things.

**Comment by jaraco** [comment]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on Aug 31, 2019, 14:11

closed
