### ISSUE TITLE
TypeError on import of v0.21 on Travis under Python 3.8-dev

### ISSUE THREAD

**Issue by jaraco** [python/importlib_metadata#87]
In GitLab by [@bskinn](https://gitlab.com/bskinn) on Sep 10, 2019, 15:57

Travis CI job that just started failing today (10 Sep 2019) is [here](https://travis-ci.org/bskinn/stdio-mgr/jobs/583236603).

Jobs on <=3.7 are passing fine, so this might imply a change in Python behavior from 3.7->3.8?  If so, not clear why the repo's [py38 CI job](https://gitlab.com/python-devs/importlib_metadata/-/jobs/291700415) passed ok. 

Travis was using v3.8.0b4+, FWIW.

Full traceback:

```
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.8-dev/bin/pytest", line 6, in <module>
    from pytest import main
  File "/home/travis/virtualenv/python3.8-dev/lib/python3.8/site-packages/pytest.py", line 6, in <module>
    from _pytest.assertion import register_assert_rewrite
  File "/home/travis/virtualenv/python3.8-dev/lib/python3.8/site-packages/_pytest/assertion/__init__.py", line 6, in <module>
    from _pytest.assertion import rewrite
  File "/home/travis/virtualenv/python3.8-dev/lib/python3.8/site-packages/_pytest/assertion/rewrite.py", line 20, in <module>
    from _pytest.assertion import util
  File "/home/travis/virtualenv/python3.8-dev/lib/python3.8/site-packages/_pytest/assertion/util.py", line 5, in <module>
    import _pytest._code
  File "/home/travis/virtualenv/python3.8-dev/lib/python3.8/site-packages/_pytest/_code/__init__.py", line 2, in <module>
    from .code import Code  # noqa
  File "/home/travis/virtualenv/python3.8-dev/lib/python3.8/site-packages/_pytest/_code/code.py", line 11, in <module>
    import pluggy
  File "/home/travis/virtualenv/python3.8-dev/lib/python3.8/site-packages/pluggy/__init__.py", line 16, in <module>
    from .manager import PluginManager, PluginValidationError
  File "/home/travis/virtualenv/python3.8-dev/lib/python3.8/site-packages/pluggy/manager.py", line 6, in <module>
    import importlib_metadata
  File "/home/travis/virtualenv/python3.8-dev/lib/python3.8/site-packages/importlib_metadata/__init__.py", line 527, in <module>
    __version__ = version(__name__)
  File "/home/travis/virtualenv/python3.8-dev/lib/python3.8/site-packages/importlib_metadata/__init__.py", line 494, in version
    return distribution(package).version
  File "/home/travis/virtualenv/python3.8-dev/lib/python3.8/site-packages/importlib_metadata/__init__.py", line 467, in distribution
    return Distribution.from_name(package)
  File "/home/travis/virtualenv/python3.8-dev/lib/python3.8/site-packages/importlib_metadata/__init__.py", line 181, in from_name
    dists = resolver(DistributionFinder.Context(name=name))
  File "<frozen importlib._bootstrap_external>", line 1385, in find_distributions
  File "/home/travis/virtualenv/python3.8-dev/lib/python3.8/re.py", line 275, in escape
    pattern = str(pattern, 'latin1')
TypeError: decoding to str: need a bytes-like object, Context found
```

**Comment by jaraco** [comment]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on Sep 10, 2019, 16:16

This is a duplicate of #86. Let's take the discussion there.

**Comment by jaraco** [comment]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on Sep 10, 2019, 16:16

closed

**Comment by jaraco** [comment]
In GitLab by [@bskinn](https://gitlab.com/bskinn) on Sep 10, 2019, 16:17

Oops, sorry!

....ah, #86 was already closed, that's why I didn't see it.
