### ISSUE TITLE
ImportError on python3.9

### ISSUE THREAD

**Issue by jaraco** [python/importlib_metadata#92]
In GitLab by [@ghost1](https://gitlab.com/ghost1) on Oct 1, 2019, 17:28

I fetched upstream cpython today and built it (heads/master:6314abc). When i ran `pre-commit` `importlib.metadata` failed with an `ImportError`

```
batuhan@x200-trisquel:~/inspectortiger$ python3.9 -m pre_commit
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.9/site-packages/pre_commit/__main__.py", line 3, in <module>
    from pre_commit.main import main
  File "/usr/local/lib/python3.9/site-packages/pre_commit/main.py", line 8, in <module>
    import pre_commit.constants as C
  File "/usr/local/lib/python3.9/site-packages/pre_commit/constants.py", line 4, in <module>
    import importlib_metadata  # TODO: importlib.metadata py38?
  File "/usr/local/lib/python3.9/site-packages/importlib_metadata/__init__.py", line 547, in <module>
    __version__ = version(__name__)
  File "/usr/local/lib/python3.9/site-packages/importlib_metadata/__init__.py", line 509, in version
    return distribution(distribution_name).version
  File "/usr/local/lib/python3.9/site-packages/importlib_metadata/__init__.py", line 482, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/local/lib/python3.9/site-packages/importlib_metadata/__init__.py", line 182, in from_name
    dists = cls._maybe_bind(resolver, context)
  File "/usr/local/lib/python3.9/site-packages/importlib_metadata/__init__.py", line 218, in _maybe_bind
    return resolver(context)
ImportError: cannot import name 'MetadataPathFinder' from 'importlib.metadata' (/usr/local/lib/python3.9/importlib/metadata/__init__.py)
```

```
batuhan@x200-trisquel:~/inspectortiger$ python3.9 -m pip show importlib_metadata
Name: importlib-metadata
Version: 0.23
Summary: Read metadata from Python packages
Home-page: http://importlib-metadata.readthedocs.io/
Author: Barry Warsaw
Author-email: barry@python.org
License: Apache Software License
Location: /usr/local/lib/python3.9/site-packages
Requires: zipp
Required-by: pre-commit
```

**Comment by jaraco** [comment]
In GitLab by [@ghost1](https://gitlab.com/ghost1) on Oct 2, 2019, 15:05

https://bugs.python.org/issue38342

**Comment by jaraco** [comment]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on Oct 26, 2019, 18:34

As resolved in the upstream issue, this issue was only due to installing Python 3.8+ over an older Python 3.8 or 3.9 beta. [Workaround](https://bugs.python.org/issue38342#msg353736) is easy. Sorry for the trouble.

**Comment by jaraco** [comment]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on Oct 26, 2019, 18:34

closed
