### ISSUE TITLE
Failed to import when the path has a resticted directory

### ISSUE THREAD

**Issue by jaraco** [python/importlib_metadata#94]
In GitLab by [@afazekas](https://gitlab.com/afazekas) on Oct 22, 2019, 12:05

````
[stack@controller-02 ~]$ cat /tmp/test.py 
import importlib_metadata
[stack@controller-02 ~]$ PYTHONPATH=/root python3 /tmp/test.py
Traceback (most recent call last):
  File "/tmp/test.py", line 1, in <module>
    import importlib_metadata
  File "/opt/stack/importlib_metadata/importlib_metadata/__init__.py", line 547, in <module>
    __version__ = version(__name__)
  File "/opt/stack/importlib_metadata/importlib_metadata/__init__.py", line 509, in version
    return distribution(distribution_name).version
  File "/opt/stack/importlib_metadata/importlib_metadata/__init__.py", line 482, in distribution
    return Distribution.from_name(distribution_name)
  File "/opt/stack/importlib_metadata/importlib_metadata/__init__.py", line 183, in from_name
    dist = next(dists, None)
  File "/opt/stack/importlib_metadata/importlib_metadata/__init__.py", line 452, in <genexpr>
    return (item for item in root.iterdir()
  File "/usr/lib64/python3.7/pathlib.py", line 1090, in iterdir
    for name in self._accessor.listdir(self):
PermissionError: [Errno 13] Permission denied: '/root'
[stack@controller-02 ~]$ 
````

````
[stack@controller-02 ~]$ PYTHONPATH=/notexisting python3 /tmp/test.py
[stack@controller-02 ~]$ 
````

Permission denied should be handled as not exsting ones.
All file permission issue should be silent at module search time.

**Comment by jaraco** [comment]
In GitLab by [@afazekas](https://gitlab.com/afazekas) on Oct 22, 2019, 12:06

changed the description

**Comment by jaraco** [comment]
In GitLab by [@afazekas](https://gitlab.com/afazekas) on Oct 22, 2019, 12:07

changed the description

**Comment by jaraco** [comment]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on Oct 26, 2019, 18:43

Yes, that seems reasonable, especially as that seems to be the way Python itself handles paths on the path that are denied for permissions:

```
importlib_metadata master $ mkdir access_denied                                                                                                                           
importlib_metadata master $ chmod 0 access_denied                                                                                                                         
importlib_metadata master $ ls access_denied                                                                                                                              
ls: access_denied: Permission denied
importlib_metadata master $ env PYTHONPATH=access_denied python -c "import foo"                                                                                           
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'foo'
```

(it silently passed on the `access_denied` directory and found no such module `foo`).

**Comment by jaraco** [comment]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on Nov 30, 2019, 11:12

I'll try to get a fix for this out as soon as the issues with the 1.0 release are rolled out. Also, merge requests are welcome.

**Comment by jaraco** [comment]
In GitLab by [@cwillenbrock](https://gitlab.com/cwillenbrock) on Jan 9, 2020, 15:30

Running into this issue as well (though hitting the permissions issue at the root.is_dir() call instead):
```
[cwillenbrock@c3cu2 ~]$ sudo -u otheruser python
Python 2.7.5 (default, Jun 20 2019, 13:30:36) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-36.0.1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import importlib_metadata
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/lib/python/importlib_metadata/__init__.py", line 554, in <module>
    __version__ = version(__name__)
  File "/opt/lib/python/importlib_metadata/__init__.py", line 516, in version
    return distribution(distribution_name).version
  File "/opt/lib/python/importlib_metadata/__init__.py", line 489, in distribution
    return Distribution.from_name(distribution_name)
  File "/opt/lib/python/importlib_metadata/__init__.py", line 190, in from_name
    dist = next(dists, None)
  File "/opt/lib/python/importlib_metadata/__init__.py", line 432, in <genexpr>
    for path in map(cls._switch_path, paths)
  File "/opt/lib/python/importlib_metadata/__init__.py", line 456, in _search_path
    if not root.is_dir():
  File "/opt/lib/python/pathlib2/__init__.py", line 1646, in is_dir
    return S_ISDIR(self.stat().st_mode)
  File "/opt/lib/python/pathlib2/__init__.py", line 1436, in stat
    return self._accessor.stat(self)
  File "/opt/lib/python/pathlib2/__init__.py", line 585, in wrapped
    return strfunc(str(pathobj), *args)
OSError: [Errno 13] Permission denied: '.'
```

It sounds like the fix would be looping through the list of paths and filtering out the ones that aren't readable by the process owner prior to having them examined by any other code. It's not entirely clear to me where the cleanest place for that change is. Before I spend more time diving into it, any sense of whether you might have the fix knocked out in the near future?

**Comment by jaraco** [comment]
In GitLab by [@cwillenbrock](https://gitlab.com/cwillenbrock) on Jan 9, 2020, 21:48

mentioned in merge request !103

**Comment by jaraco** [comment]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on Jan 11, 2020, 03:52

I suspect this issue may have been incidentally addressed in the 1.4 release with !106. I'd like to see a test to capture this expectation so it's not lost.

**Comment by jaraco** [comment]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on Jan 11, 2020, 14:55

mentioned in commit 054749eafd3acab0602deb7015e4804c15209e9d

**Comment by jaraco** [comment]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on Jan 11, 2020, 14:55

mentioned in commit 613704cdf1d325d073ab704698962feb69ac22e8

**Comment by jaraco** [comment]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on Jan 11, 2020, 15:04

mentioned in merge request !107

**Comment by jaraco** [comment]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on Jan 11, 2020, 15:06

mentioned in commit 19815ed19d64344cc33300922e218dc2cfb1d6c5

**Comment by jaraco** [comment]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on Jan 11, 2020, 15:08

In !107, I've demonstrated that this issue was fixed with the 1.4.0 release. I'd still like a test, and I've proposed one there, but I'm closing this issue.

**Comment by jaraco** [comment]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on Jan 11, 2020, 15:08

closed

**Comment by jaraco** [comment]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on Jan 11, 2020, 15:10

mentioned in commit bc93d0f013715edf8c694961d5d98d9e27f43aa4
