### ISSUE TITLE
EntryPoint objects are not pickleable

### ISSUE THREAD

**Issue by jaraco** [python/importlib_metadata#96]
In GitLab by [@asottile](https://gitlab.com/asottile) on Nov 29, 2019, 01:08

importlib-metadata==0.23, python3.6

```pycon
>>> import pickle
>>> import importlib_metadata
>>> ep = importlib_metadata.EntryPoint('foo', 'bar', 'baz')
>>> pickle.dumps(ep)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 41, in __getnewargs__
  File "/home/asottile/workspace/flake8/venv/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 125, in __iter__
    return iter((self.name, self))
RecursionError: maximum recursion depth exceeded while calling a Python object
```

I'll need to do something else for flake8 it seems :thinking: 

Same happens in python3.8 -- should I report this to bpo instead for future issues?

**Comment by jaraco** [comment]
In GitLab by [@asottile](https://gitlab.com/asottile) on Nov 29, 2019, 01:34

mentioned in merge request pycqa/flake8!388

**Comment by jaraco** [comment]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on Nov 30, 2019, 01:52

> should I report this to bpo instead for future issues?

Personally, I prefer here for now.

**Comment by jaraco** [comment]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on Nov 30, 2019, 01:56

mentioned in commit 790dd9f981bdfa10a8384a3591e725e66743e6c8

**Comment by jaraco** [comment]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on Nov 30, 2019, 01:56

mentioned in commit 1c114e212b967a3afab635e6b0b6e2bb270dac91

**Comment by jaraco** [comment]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on Nov 30, 2019, 01:58

mentioned in commit 74c3e35b9351857d5e1a9c22fd6146990114f2c5

**Comment by jaraco** [comment]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on Nov 30, 2019, 17:02

mentioned in commit 5f8baf1bb0a1596011e4ad875e94f8a4d0c60a09

**Comment by jaraco** [comment]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on Nov 30, 2019, 17:02

mentioned in commit f2859b43ad88cb84572f12ba85c546d9dc72b6ff

**Comment by jaraco** [comment]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on Nov 30, 2019, 17:30

mentioned in commit cf13944a63ef3fb8577b3edc5ba247ad73d778a3

**Comment by jaraco** [comment]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on Nov 30, 2019, 17:30

mentioned in commit dc8a5372b2e6f1ed7f77d6a6551251e07968fc36

**Comment by jaraco** [comment]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on Dec 1, 2019, 15:25

I'm going to proceed with the surgical fix for this issue, but can re-explore a more substantive change in another ticket.

**Comment by jaraco** [comment]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on Dec 1, 2019, 15:28

closed via merge request !99

**Comment by jaraco** [comment]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on Dec 1, 2019, 15:28

mentioned in commit e226573031df1bcc946619d8744a4ec9fc5b5a1f
