### ISSUE TITLE
Tests no longer pass on Python 3.4

### ISSUE THREAD

**Issue by jaraco** [python/importlib_metadata#99]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on Nov 30, 2019, 02:16

**Comment by jaraco** [comment]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on Nov 30, 2019, 02:20

Although tests passed on the current master against Python 3.4 with the 0.24 release, re-running [that pipeline](https://gitlab.com/python-devs/importlib_metadata/-/jobs/365481350) now fails. It's time to drop support for Python 3.4.

My plan is to disable the tests to allow the release of 1.0 with declared support for Python 3.4 and then drop it.

**Comment by jaraco** [comment]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on Nov 30, 2019, 02:23

Error is here:

```
py34 create: /builds/python-devs/importlib_metadata/.tox/py34
py34 develop-inst: /builds/python-devs/importlib_metadata
ERROR: invocation failed (exit code 1), logfile: /builds/python-devs/importlib_metadata/.tox/py34/log/py34-1.log
================================== log start ===================================
DEPRECATION: Python 3.4 support has been deprecated. pip 19.1 will be the last one supporting it. Please upgrade your Python as Python 3.4 won't be maintained after March 2019 (cf PEP 429).
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Collecting pip<19.1
  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.",)': /simple/pip/
  WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.",)': /simple/pip/
  WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.",)': /simple/pip/
  WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.",)': /simple/pip/
  WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.",)': /simple/pip/
  Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.",)) - skipping
  ERROR: Could not find a version that satisfies the requirement pip<19.1 (from versions: none)
ERROR: No matching distribution found for pip<19.1
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.",)) - skipping
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.4/subprocess.py", line 558, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '('/builds/python-devs/importlib_metadata/.tox/py34/bin/python', '-m', 'pip', 'install', 'pip<19.1')' returned non-zero exit status 1

=================================== log end ====================================
```

**Comment by jaraco** [comment]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on Nov 30, 2019, 02:26

mentioned in commit 1c0b1268d308a0f86e78f061dd773c882f8c89b9

**Comment by jaraco** [comment]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on Nov 30, 2019, 20:15

closed via commit 760c9e1e1592b7d993ec1067ef2b105d629d3d09

**Comment by jaraco** [comment]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on Nov 30, 2019, 20:16

mentioned in commit 0e12df728e89e3c650b91c556f1bb308347864a5

**Comment by jaraco** [comment]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on Nov 30, 2019, 20:21

mentioned in commit 760c9e1e1592b7d993ec1067ef2b105d629d3d09

**Comment by jaraco** [comment]
In GitLab by [@warsaw](https://gitlab.com/warsaw) on Nov 30, 2019, 23:28

I ran into the same problem on another project using the same images, and I made the same decision to just drop 3.4 support.
